### ISSUE TITLE
iOS Making repeated Ephemeral Key calls

### ISSUE THREAD

**Issue by moazkh60** [stripe/stripe-ios#1036]
## Summary
Stripe requesting ephemeral key repeatedly on every app restart in iOS App, while on android it's not requesting on every restart which is the correct behavior as the expiry is more. My guess is that there is an issue with the expiry of Ephemeral Key in iOS SDK.

## Code to reproduce

class StripeAPIClient: NSObject, STPEphemeralKeyProvider{
    
    static let sharedClient = StripeAPIClient()
    .
    .
func createCustomerKey(withAPIVersion apiVersion: String, completion: @escaping STPJSONResponseCompletionBlock) {}

}

// I am calling these two lines on my Home screen (which is the first tab out 4)
let _ =  StripeAPIClient.init()
let _ = STPCustomerContext(keyProvider: StripeAPIClient.sharedClient)

## iOS version
iOS 11

## Installation method
1. Using cocoa pods
2. StripeAPIClient from example project 

## SDK version
- 13.1.0

**Comment by danj-stripe** [comment]
Hi @moazkh60,

It looks like the `STPCustomerContext` refreshes the ephemeral key every hour, and it'll do it when the app is foregrounded:

https://github.com/stripe/stripe-ios/blob/b787351d6139d4114cfd68d02583420683b21c5f/Stripe/STPEphemeralKeyManager.m#L61-L65

If you're seeing it refresh more frequently, here are some things that might cause it:

1. Are you creating a new `STPCustomerContext` every time you foreground the app? A new object would need a new key.
2. Is the clock set correctly on the device? If it's set in the future, it might be expiring the key too soon.

Otherwise, you might use the debugger and step through `STPEphemeralKeyManager handleWillForegroundNotification ` to see why it thinks it needs to refresh more often.

Finally, I don't think it's a problem if your app requests a new ephemeral key every time it foregrounds. It's certainly inefficient, but I'd expect everything to keep working.
