### ISSUE TITLE
Update Stripe's documentation on tokenization

### ISSUE THREAD

**Issue by lfarah** [stripe/stripe-ios#111]
![screen shot 2015-01-19 at 5 37 15 pm](https://cloud.githubusercontent.com/assets/6511079/5810851/e16bf486-a001-11e4-86fe-018d53a11a7d.png)
 Stripe's documentation tell's us to use:

    + (void)createTokenWithPayment:(PKPayment *)payment completion:(STPCompletionBlock)handler     __attribute__((deprecated));

but Xcode told me that this method was unavailable, so I checked and this method is actually deprecated, and we're supposed to use this instead:

    [[STPAPIClient sharedClient] createTokenWithPayment:completion:]

**Comment by tosha9** [comment]
How would I use in Swift controller???

**Comment by kiritym** [comment]
STPAPIClient.sharedClient().createTokenWithPayment(payment, completion: { (token: STPToken!, error: NSError!) -> Void in
                if error != nil {
                    //handle token to create charge in backend
                    completion(PKPaymentAuthorizationStatus.Failure)
                }else {
                    completion(PKPaymentAuthorizationStatus.Success)
                }

**Comment by jflinter** [comment]
Cool, I've fixed the references to deprecated API methods on stripe.com/docs/mobile/ios . Still to do: update with Swift examples. I've opened #122 for this. Thanks!

**Comment by felixdkatt** [comment]
I'm getting weird error with this
STPAPIClient.sharedClient().createTokenWithPayment(payment, completion: { (token, error) -> Void in

in swift 2.0 gives me....

PaymentController.swift:209:75: Invalid conversion from throwing function of type '(_, _) throws -> Void' to non-throwing function type 'STPCompletionBlock' (aka '(Optional<STPToken>, Optional<NSError>) -> ()')

I understand that stripe is in objective C but im not able to make the method call that was working before in swift 1.2 . Is there an example for swift 2.0 somewhere? The problem is the method call not the rest of my code. Error is highlighting this method call

**Comment by akinmobile** [comment]
@felixdkatt  Hi You can make the call this way 

 STPAPIClient.sharedClient().createTokenWithPayment(payment, completion: { (token: STPToken?, error: NSError?) -> Void in
                
                print(token)
})

I hope this helps..
