### ISSUE TITLE
STPFormTextField should be public

### ISSUE THREAD

**Issue by osrl** [stripe/stripe-ios#1135]
## Summary
STPFormTextField and it's companion classes should be public. It's very common to use a custom ui instead of `STPPaymentCardTextField`

## Other information
Controls like `CardNumberEditText` and `ExpiryDateEditText` are already public on Android and it was very easy to use them for a custom ui. It's a bit disappointing that I should copy paste the source to my project.

Is there an ETA for this? Thanks

**Comment by csabol-stripe** [comment]
Hi @osrl, 

I don't have an ETA right now, but I've added this to our internal project planning and we'll work on getting it scheduled. Thanks for the request!

**Comment by WHeB** [comment]
When will it be resolved?

**Comment by csabol-stripe** [comment]
I wanted to provide an update here:

`STPFormTextField` has never gotten to the point where we feel comfortable offering it in our public API. As part of our newly released PaymentSheet integration, we re-worked how we are handling text field inputs and will be focusing on those new classes in the future. So there are no plans to make `STPFormTextField` public.

To the point of giving our developers more customization options, that is something that is very top-of-mind. Because interacting directly with a text field that contains credit card numbers could make you ineligible for a PCI SAQ A (see https://stripe.com/docs/security/guide for more details), we want to make sure that we add customization options that can maintain PCI compliance and just offering a standalone card number text field is not something on our roadmap.

We will be considering additional options here but I do not have a timeline to share currently. 

Because this request is specifically for `STPFormTextField` I am going to close this issue but please feel free to file additional requests for customization that we can use to inform our API designs :)

**Comment by osrl** [comment]
Hello @csabol-stripe thanks, fair enough. But, how about android? Those classes are already public on Android. Aren't those security concerns valid for Android too?
