### ISSUE TITLE
Check if stored card supports 3D Secure

### ISSUE THREAD

**Issue by matibzurovski** [stripe/stripe-ios#1138]
## Summary
I am working on an app that allows the user to add credit cards and make payments with them later. The flow is pretty simple:
- User adds the new card details on the app.
- App generates a token with the `STPAPIClient`, and stores the object in the server. We keep the `token`, `name` and `expirationDate`. But we don't keep the `number` nor the `cvc` for security reasons.
- User makes a purchase on the app, which asks the server to trigger the Stripe process (using the token generated on previous step).

The problem is that, for some suspicious purchases, we may need to request a 3D secure verification. I have followed [this](https://github.com/stripe/stripe-ios/blob/master/Example/Custom%20Integration%20(ObjC)/ThreeDSExampleViewController.m#L116) example, and it works fine if I know the `number` and `cvc`. 
However, as I have mentioned, we don't keep this information. So basically my question is how can I create the `STPCardParams` using the card token, instead of using the `number` and `cvc`.

## iOS version
11

## Installation method
Cocoapods

## SDK version
`12.1.2`

**Comment by aliriaz-stripe** [comment]
Hi Matias,
You should create STPSource from the user's card details in order to use 3DS. You can the `createCardSources` flag on `STPPaymentConfiguration` to default to creating STPSource objects instead of the default STPCard objects (if using Stripe's view controllers to collect card details).

You can then retrieve the Source using `STPAPIClient.shared().retrieveSourceWithId()` to retrieve the STPSource object and use it when creating the STPRedirectContext for 3DS verification.

Hope that helps!
If you have any more integration questions, feel free to write in to https://support.stripe.com/ where we'll be able to better assist you!
