### ISSUE TITLE
[Stripe SDK 14.0] Standard integration saving cards automatically

### ISSUE THREAD

**Issue by alexis-letexier** [stripe/stripe-ios#1150]
Hello,

I'm using the standard integration to handle the payments methods of a customer (using `STPBackendAPIAdapter` for now).

When a user add and select a payment method, the Stripe SDK will automatically save the source to the stripe customer account. For legal purposes we want the approval of the customer to save his card to his stripe account or not save the card at all if possible.

Can we do that ?

Thanks a lot !

**Comment by csabol-stripe** [comment]
Hi @alexis-letexier, to do this you would have to use a custom implementation of `STPBackendAPIAdapter` instead of using the provided `STPCustomerContext`. You could then override `- (void)attachSourceToCustomer:(id<STPSourceProtocol>)source completion:(STPErrorBlock)completion` to prompt the customer and initialize your `STPPaymentContext` with your custom API adapter `- (instancetype)initWithAPIAdapter:(id<STPBackendAPIAdapter>)apiAdapter` Feel free to write in to support to have our developer relations team help with any issues you have here :)
