### ISSUE TITLE
 ERROR ITMS-90535: "Unexpected CFBundleExecutable Key"

### ISSUE THREAD

**Issue by attheodo** [stripe/stripe-ios#1154]
## Summary
Started ITMS getting errors when trying to upload our app to App Store Connect. 

```
ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/[REDACTED].app/Frameworks/Stripe.framework/Stripe.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."

Return status of iTunes Transporter was 1: ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/[REDACTED].app/Frameworks/Stripe.framework/Stripe.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."
```

## Installation method
```
$ pod --version
1.7.0.beta.3
```
Same problem with the last stable Cocoapods.

## SDK version
```
$ cat Podfile.lock | grep Stripe
  - Stripe (15.0.0)
  - Stripe
    - Stripe
  Stripe: 312b22a67af9fa55c246d26148b3f3a9636a0ff2
```
Xcode 10.2 - Swift 5.0

- We've checked that we do not have any items in the `Copy Bundle Resources` (like any .plist files or Target Support Files) build phase that might result in this issue. 
- We've also manually tried to remove `CFBundleExecutable` key from Stripe's .plist file, again with no success.

Please advise. Thank you!

**Comment by attheodo** [comment]
Looks like this was a result of the project ending up misconfigured. Not sure how it ended up like so but de-integrating pods and re-install them seems to have fixed the issue:

```
$ pod deintegrate
$ pod install
```

**Comment by attheodo** [comment]
Any updates on this? This is really blocking our whole release process. Thanks!

**Comment by rromanchuk** [comment]
+1

**Comment by slhodson969** [comment]
+1

This is now blocking our release

**Comment by rromanchuk** [comment]
@attheodo @slhodson969 have you guys spent any more time investigating this? it's strange because I can cut a release via fastlane locally without issue, it's only on `circleci` where i'm getting this.... The environment is locked down (should be at least) to the same as development/local environments, so there shouldn't be **that** many variables involved, it has to be something subtle.

**Comment by attheodo** [comment]
@rromanchuk I haven't had the time yet. I was hoping for something quick from Stripe's end since they probably have more bandwidth but since has dragged us for about a week now, I'll probably spend some time investigating.

I am wondering what the hell it could be on CI that's mutating .plist files post-build; really weird. We don't even install/configure pods, we have them pre-commited and configured when they hit Circle.

Could you please share your local `fastlane`, `gym`/`build` and `testflight`/`pilot` and `cocoapod` versions so we can cross compare? Also are you using the pre-bundled versions of those on Circle's 10.2 image?

**Comment by rromanchuk** [comment]
@attheodo that's funny, we also have our pods committed, did it to avoid complexity. I'm using their `10.2` image, but our config is insane because it's a ton of work to get `2.6.3` installed, some brew utilities, bundler, etc etc... and then make a best effort to cache so builds don't take 14 hours. My lockfiles are locked to ruby version and i didn't want to compromise just for CI.

I should run a `bundle exec pod deintegrate && bundle exec pod install` and see if there is some sort cruft/artifacts left behind. When i get back i'll post env details. I should probably clone the project from scratch and purge my build/cache directories and see if i'm able to reproduce.

**Comment by jspargo** [comment]
@rromanchuk @attheodo we hit a similar issue and it was because CircleCI are not using the release version of Xcode 10.2, they're still using Xcode 10.2 Beta 3 (Apple don't allow uploads to App Store Connect from beta versions of Xcode). There's some more info [here](https://discuss.circleci.com/t/unexpected-cfbundleexecutable-key-the-bundle-at-payload-myapp-app-firebaseauthui-bundle-does-not-contain-a-bundle-executable/29524) but our solution was to revert back to using Xcode 10.1 on CircleCI until they provision a macos VM that uses the release Xcode 10.2 version.

**Comment by jspargo** [comment]
I should also add - there is a workaround (I've not tried) that uses xcode-install to remove 10.2, then reinstall it (which fetches the release version): https://gist.github.com/lokst/3985c1d7610afde9f8a75b79a36496ed

**Comment by attheodo** [comment]
@jspargo that's really helpful info. I didn't realize Xcode on CircleCI is a beta version. According to the [manifest](https://circle-macos-docs.s3.amazonaws.com/image-manifest/build-520/index.html) it's not.

**Comment by jspargo** [comment]
@attheodo yeh, it's really badly labelled in the manifest as it says:
```
With Xcode 10.2 Build 10P99q we pre-install the following simulators:
```
but according to https://xcodereleases.com/ these are the builds for Xcode 10.2:
```
Xcode 10.2 | GM     | 10E125
Xcode 10.2 | Beta 4 | 10P107d
Xcode 10.2 | Beta 3 | 10P99
```

**Comment by attheodo** [comment]
Right 🤦‍♂️ ... Looks like this is not on the Stripe-folks end.
