### ISSUE TITLE
Stripe Integration in React Native

### ISSUE THREAD

**Issue by mahipalsingh7** [stripe/stripe-ios#1197]
Hello team i need to integrate Stripe payment gateway in React Native Hybrid apps, could you please help me with the steps or any supportive link for Stripe Integration in React Native.

**Comment by dziter** [comment]
Hey @mahipalsingh7,

I just contacted Stripe support online about this point too because of SCA compliance:
https://stripe.com/docs/strong-customer-authentication

If you don't mind about SCA (no European Customers), you could do your requests on Stripe API with custom RN forms or using Tipsi lib for example:
https://github.com/tipsi/tipsi-stripe

Have a good day!

**Comment by yuki-stripe** [comment]
+1 to the suggestions!  and re: SCA & tipsi - we're working on this over the next few weeks.  https://github.com/tipsi/tipsi-stripe/issues/448

I'm going to close this issue, feel free to reply though @mahipalsingh7
