### ISSUE TITLE
Additional methods to store/retrieve customer/card data

### ISSUE THREAD

**Issue by jflinter** [stripe/stripe-ios#121]
Strawman title: STPCardWallet

Note: this may require making some APIs publishable-key accessible, which we may or may not want to do.

**Comment by kamarshad** [comment]
Hello @jflinter 

I am using stripe iOS sdk for payment processing in my iOS application.
I am creating custom UI to collect user card details(and other details too).
Is there any way to save that retrieved card details (on stripe end since we don't need to worry about PCI compliance)we could display it again whenever user come again for payment(kind of remember me functionality).
Is it possible to integrate such functionality (using custom UI form) through the stripe.

Please help me 
Thanks !!

**Comment by jflinter** [comment]
Hey @kamarshad - you should do this on your backend, by creating a stripe customer - see https://stripe.com/docs/api#customers . We don't have any specific UI components for this now, but it's something we're looking into.
