### ISSUE TITLE
Unable to get Stripe token didCreateToken token: STPToken is not getting called 

### ISSUE THREAD

**Issue by Milap-Kundalia** [stripe/stripe-ios#1247]
I am using stripe in my app as a payment gateway. I was getting token in 

**func addCardViewController(_ addCardViewController: STPAddCardViewController, didCreateToken token: STPToken, completion: @escaping STPErrorBlock)**

but I think after I updated my pods didCreateToken token: STPToken is not getting called and I am unable to get token. Instead of **didCreateToken** **didCreatePaymentMethod** is getting called and I am getting payment method. Can you please let me know how to get stripe token.

Current stripe pod version is Stripe 16.0.0

**Comment by yuki-stripe** [comment]
Hi @Milap-Kundalia.  You're seeing the expected behavior - we've migrated to the [Payment Methods API](https://stripe.com/docs/payments/payment-methods#transitioning).  You'll need to stay on a previous version or migrate your integration.

See [MIGRATING.md](https://github.com/stripe/stripe-ios/blob/master/MIGRATING.md#migrating-from-versions--1600) for all the breaking changes for every version.

**Comment by 01234abhishek** [comment]
I also facing same problem, didCreateToken is not calling current pod version  '19.0.1'. 
Thanks

**Comment by aliriaz-stripe** [comment]
@01234abhishek hello, I'm assuming you're not getting the `didCreateToken()` delegate isn't triggering from STPAddCardViewController? 

If so, that is expected after versions v16.0.0, the `didCreateToken()` delegate is deprecated and you should be leveraging `didCreatePaymentMethod()` instead (which creates a PaymentMethod object instead of a Token object)

**Comment by 01234abhishek** [comment]
In didCreatePaymentMethod I am getting the stripeId, I need the token. Can you please help me

**Comment by aliriaz-stripe** [comment]
@01234abhishek you'll have to roll back to stripe-ios before v16.0.0 for the `didCreateToken()` delegate to work for you as it was deprecated after that.

**Comment by 01234abhishek** [comment]
@aliriaz-stripe Thank a lot for your guidance. It means a lot. actually I stuck in this scenario. I am using pod pod 'Stripe', '19.3.0', so according to you I am integrating pod 'Stripe', '16.0.0'. then it will work , right?

**Comment by aliriaz-stripe** [comment]
@01234abhishek so you want to hop on to a version before v16.x.x, so you should pin to 
`pod 'Stripe', '15.0.1' `

**Comment by 01234abhishek** [comment]
@aliriaz-stripe Thank You very much.

**Comment by 01234abhishek** [comment]
@@aliriaz-stripe  Thank You very much. It is working. Thanks a lot
