### ISSUE TITLE
Request failed. Unsupported content-type: text/html

### ISSUE THREAD

**Issue by jiangning93** [stripe/stripe-ios#125]
Hi there, 
I am trying to use the stripe ios sdk sample according to stripe/stripe-ios (Getting started with the Simple iOS Example App):
 

 However, when  I run the "custom" app it always give the following errror:Request failed. Unsupported content-type: text/html 
Please see the attached for details. 

I have contacted the support team and was asked to file an issue for it. Could you please help

Thanks,
Ning

![error](https://cloud.githubusercontent.com/assets/2084929/6714551/16f89ec0-cd56-11e4-8ef2-24837c14ff1b.png)

**Comment by matthewarkin** [comment]
Did you do steps 3 and 4 of the "Running the Example App" part of the read me?

> - Head to https://github.com/stripe/example-ios-backend and click "Deploy to Heroku" (you may have to sign up for a Heroku account as part of this process). Provide your Stripe test secret key for the STRIPE_TEST_SECRET_KEY field under 'Env'. Click "Deploy for Free".
- Replace the backendChargeURLString variable in the example iOS app with the app URL Heroku provides you with (e.g. "https://my-example-app.herokuapp.com")

**Comment by Jonyzfu** [comment]
Hi Ning,

I also meet the same problem. This may mean that the deployed server is sending "text/html" instead of the already supported types. My solution was to set RequestOperationManager Response Serializer to HTTPResponseSerializer.

Add the following code after initializing the AFHTTPRequestOperationManager under ViewController.m:
manager.responseSerializer = [AFHTTPResponseSerializer serializer];

I think it's a temporary solution now, the ideal solution will be to change the deployment file from the server.

**Comment by jflinter** [comment]
#130 fixes this. Thanks @Jonyzfu!
