### ISSUE TITLE
Status bar customisation for STPThreeDSCustomizationSettings

### ISSUE THREAD

**Issue by DrTomBates** [stripe/stripe-ios#1253]
## Summary
It would be mega if we could pass in a `UIStatusBarStyle` to the `STPThreeDSCustomizationSettings`. Currently, I think it just uses the default

## Installation method
Cocoapods

## SDK version
16.0.1

**Comment by yuki-stripe** [comment]
Agreed, thanks for the feedback @DrTomBates.  We're tracking this internally.

**Comment by yuki-stripe** [comment]
@DrTomBates This will be in the next release!

**Comment by DrTomBates** [comment]
@yuki-stripe Just having a look at implementing this. It looks like I can set the status bar color only on `STDSUICustomization` I need this to be exposed through `STPThreeDSUICustomization` unless I am missing something?

**Comment by yuki-stripe** [comment]
@DrTomBates Ah you're totally right, thanks. Fixing here: https://github.com/stripe/stripe-ios/pull/1296

**Comment by yuki-stripe** [comment]
@DrTomBates FYI:

I've removed `preferredStatusBarStyle` since it doesn't actually do anything in our case (because our UIViewControllers are in a UINavigationController).  Instead, set the [barStyle](https://stripe.dev/stripe-ios/docs/Classes/STPThreeDSNavigationBarCustomization.html#/c:objc(cs)STPThreeDSNavigationBarCustomization(py)barStyle) to `.black` to set the statusBarStyle to `.lightContent`.  You can still control the color of the navigation bar via the `barTintColor` and `translucent` properties.  Confusing, but this is how it works on iOS!

Check out the summary here https://github.com/stripe/stripe-ios/pull/1308

**Comment by DrTomBates** [comment]
Thanks for the heads up @yuki-stripe 
It is indeed strange to have to set the navigation bar to black to then change it to blue, I had thought that you would have subclassed `UINavigationController` and returned the `preferedStatusBarStyle` from that.
This solution works just as well though, by the looks of it and you don't need to subclass. 
Every day is a school day.

![Simulator Screen Shot - iPhone Xs - 2019-08-22 at 15 00 59](https://user-images.githubusercontent.com/48063189/63521301-15e37700-c4ee-11e9-9b85-85d2121ee9f0.png)
