### ISSUE TITLE
STPPaymentMethod not display newly created card.

### ISSUE THREAD

**Issue by pratik1311** [stripe/stripe-ios#1328]
Hi 
I am using Stripe SDK version 16.0.5.
I download code from github and tried to run **UI Example Project**
When I first run app that time it display preloaded cards. 
I added new card but its not display in list of cards.

```
override func attachPaymentMethod(toCustomer paymentMethod: STPPaymentMethod, completion: STPErrorBlock? = nil) {
        customer.paymentMethods.append(paymentMethod)
        if let completion = completion {
            completion(nil)
        }
 }
```

Above method is called when I add new card but it's not display that newly added card. 

Do I miss something?

Thanks,
Pratik

**Comment by davidme-stripe** [comment]
Thanks for filing, this is a bug on our end. I'm fixing it in #1333.

**Comment by pratik1311** [comment]
Thank you for your reply. Please let me know when this bug is solve. 
I will be wait.

**Comment by davidme-stripe** [comment]
The bug should be resolved if you pull our current master branch from GitHub and rebuild UI Examples. We'll release it in a packaged update soon.

**Comment by pratik1311** [comment]
Hey

When I added new card then I am getting wrong `stripeId` in attach method
Newly added `paymentMethod.stripeId` should be `pm_********` but after you solve bug I am getting id like `10523555563`.

Please check and let me know.

**Comment by davidme-stripe** [comment]
That's expected when using UI Examples — it's only meant to show off the various UI elements, so it uses a mock server instead of creating real PaymentMethod IDs. If you're building a new integration, you might have a better time starting from the `Standard Integration` or `Custom Integration` projects.

If you're just starting out with Stripe, it might help to contact us via our [email and IRC support channels](https://support.stripe.com), where we're more likely to provide faster answers.
