### ISSUE TITLE
STPCard stopped working when converting from STPPAymentoption

### ISSUE THREAD

**Issue by giorgio80** [stripe/stripe-ios#1411]
hello guys, 

update to latest pod and got an "error". when  try to get cardio from select payment option method.   simply when converting to STPCard object I got a nil...

looking inside the STTPAYmentOptionObject ,  the card is btw present...

` func paymentOptionsViewController(_ paymentOptionsViewController: STPPaymentOptionsViewController, didSelect paymentOption: STPPaymentOption) {
        print("OPTION HAS BEEN SELECTED")
        paymentOpt = paymentOption
        let card = paymentOpt as? STPCard   <- GOT NIL HERE.....
        let paymentStripeId = card!.stripeID

db.collection("users").document(Auth.auth().currentUser!.uid).setData(["defaultCardID": paymentStripeId as String], merge: true)
                   print("CARD HAS BEEN INSERTED IN BACKEND")`

**Comment by yuki-stripe** [comment]
Hi @giorgio80,

It sounds like you're upgrading from a version before `v15.0.0`.  I believe you'll need to cast `paymentOption` to an `STPPaymentMethod` here instead of `STPCard`.

I'd also like to point out that `STPPaymentOption` could also be other types, depending on what `STPPaymentContext` is configured to allow - e.g. `STPApplePayPaymentOption`.

**Comment by davidme-stripe** [comment]
If you're still running into trouble with migrating to the latest version, our [support team](https://support.stripe.com/contact) should be able to provide more help. Feel free to CC either of us on the email.
