### ISSUE TITLE
Using STPPaymentOptionsViewController add card cannot succeed

### ISSUE THREAD

**Issue by zhao520wei** [stripe/stripe-ios#1522]
## Summary

 when I using STPPaymentOptionsViewController add bank card , first time , it add success ,but   then second time , I add  not success. 

In android  side ,  add bank card  success every time,  used Stripe.createToken( card: Card, object: TokenCallback) , But I can not find the method  in iOS side.

  Where I can find the way to add bank card success as android  side ? and can you tell me the reason why  second time  add not success ?

I just want add user input bank card information to StripeSDK , but I can not find the method like android

## iOS version
 
all the version

## SDK version
18.0.0

**Comment by zhao520wei** [comment]
I just want add user input bank card information to StripeSDK , but I can not find the method like android

**Comment by aliriaz-stripe** [comment]
Hello @zhao520wei , would you mind writing in to https://support.stripe.com/contact with the integration issue you're running into? 

Please include the following
- version of SDK used
- code snippet (shared via pastebin.com), showing the delegate methods you have implemented
- any steps to reproduce
- the expected behavior you'd like to see, and what you are currently seeing

Closing this as Github Issues should be limited to bugs or feature requests for the SDK.
