### ISSUE TITLE
ApplePay selected by default

### ISSUE THREAD

**Issue by tonikocjan** [stripe/stripe-ios#1639]
## Summary
If Apple Pay is available on a device, it will be selected by default in `STPPaymentOptionsViewController`, and `paymentContextDidChange(:)` delegate method will be triggered, which is causing me some difficulties with our integration.

_Edit:_

My suggestion is that a new variable is introduced (`selectApplePayByDefault` or something in this line) which would be `true` by default. That way the behavior is not changed for existing users but can be modified if necessary.

## iOS version
_Not version specific_.

## Installation method
Codoapods.

## SDK version
19.4.0

## Other information
I've narrowed the problem to https://github.com/stripe/stripe-ios/blob/master/Stripe/STPPaymentOptionTuple.m#L44.
If called for, I am able to create a pull-request resolving this.

**Comment by Ariandr** [comment]
Hi @tonikocjan 
Well, I personally don't see it as a bug, but rather as a feature. Lots of users use Apple Pay if they see it's pre-selected and our app relies on this behavior.

So, instead of changing the current behavior (which is not a bug), it could be possible to introduce a new property which will do something, but won't touch the current behavior if users of the SDK don't change their app code.

**Comment by tonikocjan** [comment]
@Ariandr that's what I had in mind, sorry for not expressing myself clearly enough. I would not alter the default behavior but rather make it configurable, just like you said.

**Comment by macbro3** [comment]
Duck you

**Comment by csabol-stripe** [comment]
@tonikocjan this is something we are exploring with our design team. Thanks for letting us know it's something you would use :)

**Comment by davidme-stripe** [comment]
We've improved this experience in [PaymentSheet](https://stripe.com/docs/payments/accept-a-payment?platform=ios&ui=payment-sheet), our modern prebuilt payments UI.
