### ISSUE TITLE
decline_code in declined case is missing

### ISSUE THREAD

**Issue by nguyenhuutinh** [stripe/stripe-ios#1755]
hi team , 
according to the document, we should get the decline_code in declined case
but I debug and found there is no decline_code in error response.
Can you tell me how to get the decline_code in declined case?

Thanks
Error Domain=com.stripe.lib Code=70 "Your card was declined" UserInfo={com.stripe.lib:ErrorMessageKey=Your card was declined., com.stripe.lib:StripeErrorCodeKey=card_declined, com.stripe.lib:StripeErrorTypeKey=card_error, com.stripe.lib:CardErrorCodeKey=com.stripe.lib:CardDeclined, NSLocalizedDescription=Your card was declined})

**Comment by yuki-stripe** [comment]
Hi @nguyenhuutinh,

We'll get this fixed in the next release. In the mean time, if you're using PaymentIntents, you may be able to find the decline code in [its lastPaymentError property](https://stripe.dev/stripe-ios/docs/Classes/STPPaymentIntent.html#/c:@M@Stripe@objc(cs)STPPaymentIntent(py)lastPaymentError)

e.g. 
`paymentIntent.lastPaymentError.declineCode`

**Comment by davidme-stripe** [comment]
This should be fixed in [21.4.0](https://github.com/stripe/stripe-ios/releases/tag/21.4.0).
