### ISSUE TITLE
ver 19.4.1 is still missing from Cocoapods and How about 20.1.2?

### ISSUE THREAD

**Issue by xuzhe** [stripe/stripe-ios#1767]
1. It's nice to have 19.4.1, but I can not update it from Cocoapods. Is there any plan to release it to Cocoapods?
2. I'am also using the 20.1.1 but not the swift version 21.x.x, is there any plan to release a Xcode 12.5 compatibility version for 20.x.x as well?

Thanks!

**Comment by davidme-stripe** [comment]
Hi @xuzhe, thanks for filing! For background, we re-released 15.0.3 to support folks who haven't migrated to PaymentIntents, 17.0.4 for iOS 9 support, and 19.4.1 for iOS 10 support.

1: It's difficult for us to re-release 19.4.1 via Cocoapods because of a quirk of our closed-source 3DS2 library. We'd prefer if folks moved to 21.3.1, which is 100% open-source and doesn't require the same hacks. The only difference should be iOS 10 support — unfortunately, the open-source 3DS2 library requires iOS 11.

iOS 10 accounts for a negligible fraction of payments in all our supported countries, and our recommendation is to drop support for it. If you're unable to do so, you can manually build the frameworks for 19.4.1 using `./ci_scripts/export_builds.sh`.

2: We don't plan to re-release 20.x.x, as 21.3.1 supports the same OS versions and requires very little migration work. Are you experiencing problems with the Swift version of the framework?

**Comment by xuzhe** [comment]
@davidme-stripe Thank you for your reply and all the details provided!

Since we also providing payment SDK to our customers which is using Stripe SDK as a plugin, it's a little bit different from just using Stripe in an independent App. Depending on the details you provided, we will start planning our new release roadmap as well.

**Comment by davidme-stripe** [comment]
I applied a hack that will allow 19.4.1 to work with Cocoapods. Note that it will prevent you from building on Apple Silicon, and we'd still recommend that you update to 21.4.0 instead. Please give it a try and let me know if you have any issues.
