### ISSUE TITLE
Stripe   v14.0.2 Localized multilingual display errors

### ISSUE THREAD

**Issue by MrChen88088** [stripe/stripe-ios#1862]
In the iOS version, when the phone language is switched to Chinese, the title, cancellation, and completion of the card adding page are all displayed in Chinese.
When the phone language is switched to English again, kill the app and enter the add card page again
Title display: "Add a card", cancel display "取消", complete display "完成"

<img width="350" alt="截屏2021-08-20 下午5 50 08" src="https://user-images.githubusercontent.com/12132487/130215353-bb13aeca-8094-4ab6-929b-bcdb232c28c9.png">

**Comment by davidme-stripe** [comment]
Hi @MrChen88088, thanks for filing this! I think the "取消" and "完成" strings are being pulled from the iOS system, not our SDK. If an app only provides a localization for Chinese but the device is set to English, I believe the system-provided UI elements (such as these Done and Cancel buttons) will use Chinese to ensure consistency with the rest of the app.

Our SDK should behave the same way and show Chinese in this situation, but I think it's displaying English because of a bug we fixed in 21.2.1. Can you try this again on version 21.2.1 or later?
