### ISSUE TITLE
Abandoned 3DS payment results in failure for subsequent payment attempts

### ISSUE THREAD

**Issue by corey-plugshare** [stripe/stripe-ios#1897]
## Summary
After abandoning a 3DS payment, all subsequent payment attempts -- even non-3DS payments -- results in a failure.

## Code to reproduce
```
func confirmPayment(_ secret: String) {
    let paymentIntentParameters = STPPaymentIntentParams(clientSecret: secret)
    paymentIntentParameters.useStripeSDK = true

    STPPaymentHandler.sharedHandler.confirmPayment(paymentIntentParameters, with: self) { [weak self] (status, _, error) in
        // Handle error
        guard error == nil else {
            // ===>>> We end up here after abandoned 3DS payment <<<===
            print("Payment confirmation returned error: \(String(describing: error?.localizedDescription))")
            return
        }

        // Error-free confirmation code goes here...
    }
}
```

## iOS version
Issue confirmed in 14.0.1, 15.0, 15.0.2

## Installation method
Cocoapods

## SDK version
Confirmed in 21.8.1, 21.9.0

## Other information
The app does not have a shopping cart and is a select-and-pay-immediately  type app. Users cannot save their purchase for later, therefore we do not save and retry payment intents. Each attempted payment generates a new payment intent. A payment is started with a 3DS card (ex: *3184), but abandoned during the authentication process in `STPAuthenticationContext.prepare(forPresentation:)`. The payment intent is left in a requires confirmation status. Shortly thereafter the user then tries to pay again with a non-3DS card (ex: *4242). This can be for the same item or a different item. The confirmation status is returned with a `STPPaymentHandlerActionStatus.failed` and the message "There was an unexpected error -- try again in a few seconds". The expected behavior is that one payment intent's status does not affect another.

**Comment by davidme-stripe** [comment]
Hi @corey-plugshare, thank you for the bug report! I tried this locally, but I'm unable to reproduce it with the test cards you mentioned.

* Would it be possible to print the `error.userInfo[STPError.errorMessageKey]` from the NSError? Or even the entire error.userInfo dictionary?
* Is it possible that your `authenticationPresentingViewController` is already presenting another view?
* It might help if you could provide some PaymentIntent `pi_` IDs so we can follow the confirmation attempt on the backend. This is a public forum, so that sort of debugging might be better handled via support@stripe.com.

Hope we can help debug this!

- David

**Comment by corey-plugshare** [comment]
Hi David! Thanks for the quick reply.

- Would it be possible to print the error.userInfo[STPError.errorMessageKey] from the NSError? Or even the entire error.userInfo dictionary?

```
["NSLocalizedDescription": "There was an unexpected error -- try again in a few seconds", "com.stripe.lib:ErrorMessageKey": "The current action is not yet completed. STPPaymentHandler does not support concurrent calls to its API."]
```

That is an interesting message. I read that as if some action needs to take place on the previous payment intent before proceeding with this new one. When I said above that we abandon the payment flow, I meant that very literally. No indication of abandonment or cancellation is sent to our backend or to Stripe. We simply do nothing more with that intent.

- Is it possible that your authenticationPresentingViewController is already presenting another view?

That is highly unlikely. We are adding a minimal payment flow into CarPlay and cannot support authentication because it is not based on UIKit, so a UIViewController cannot be supplied to `authenticationPresentingViewController()`. Without a way to know if a payment source will require authorization prior to creating a payment intent, all we can really do  is abandon the flow if `prepare(forPresentation:)` is called by Stripe. We admit that this is not the best solution for this scenario but it is our MVP. Perhaps the best solution will be to handoff to the iOS device for authentication, but we have no mechanism for that just yet and don't have the time to create it before release.

- It might help if you could provide some PaymentIntent pi_ IDs so we can follow the confirmation attempt on the backend. This is a public forum, so that sort of debugging might be better handled via support@stripe.com.

I'd be happy to do so if it is safe to do. This is just in testing right now and is not using our production account, but I do not know if that is safe to do here even for testing.

**Comment by davidme-stripe** [comment]
Because `STPPaymentHandler` is getting stuck in this state, it sounds like it is getting a valid UIViewController from somewhere and attempting to present a sheet over it. Is it possible that your `authenticationPresentingViewController()` is returning a hidden view controller from the iPhone scene's view hierarchy?

For your MVP, try adding this hack to your `STPAuthenticationContext`:
```
func authenticationPresentingViewController() -> UIViewController {
  return UIViewController()
}
```
This should fail 3D Secure payments with an error, as the new UIViewController won't exist in the view hierarchy and can't be presented. Then check `if error.code == STPPaymentHandlerErrorCode.requiresAuthenticationContextErrorCode`, and show the user a message that 3D Secure authentication isn't supported in CarPlay.

For the eventual handoff solution, you could implement `prepare(forPresentation completion:)` in your `STPAuthenticationContext`:
```
func prepare(forPresentation completion: @escaping STPVoidBlock) {
    // Present a CPAlertTemplate telling the user to complete authentication on their phone
    // Prepare the phone-side scene to show the authentication view controller
    // When you're ready, run the provided completion block, which will call `authenticationPresentingViewController()` and present the authentication sheet
    completion()
}
```

CarPlay is a very interesting use case — we'll try to think of a better way to handle this. Presenting an Apple Pay sheet on the iPhone could be a good solution too, as it never requires 3DS1/3DS2 authentication.

Hope that helps!

**Comment by corey-plugshare** [comment]
Thank you so much, you helped me find the solution. I was already doing something similar to what you suggested by passing back a view controller that was not in the hierarchy if the presentation layer did not return one, which the CarPlay implementation does not:

```
func authenticationPresentingViewController() -> UIViewController {
    return presenter?.presentationViewController(for: self) ?? UIViewController()
}
```

My issue was that I misunderstood the order of operation and I thought that `prepare(forPresentation:)` was called before `authenticationPresentingViewController()`, so I had code in prepare that abandoned the flow thinking that would end it not realizing that `authenticationPresentingViewController()` had been called already. As you can see below I was intentionally not calling the completion handler to abandon the process:

```
func prepare(forPresentation completion: @escaping STPVoidBlock) {
    guard presenter?.presentationViewController(for: self) != nil else {
        error(.unableToProcessPayment,
            message: "Presentation delegate did not return a UIViewController for Stripe authentication")
        return
    }
    completion()
}
```

It appears that bailing out of the process in `prepare(forPresentation:)` was what was causing my issue. By removing that prepare code and allowing the flow to continue, I am now able to trap for the error in `STPPaymentHandler.sharedHandler.confirmPayment(:with:)` when using the *3184 card and then immediately try again with the *4242 card successfully. So, thank you again for helping me understand that.

Your suggestion of using `prepare(forPresentation:)` as the point to initiate the handoff from CarPlay to phone makes a lot of sense. Or, maybe by the time I get around to it you guys will already have a slick implementation for CarPlay. ;)

I really appreciate you helping me with this.
