### ISSUE TITLE
[BUG] Unable to subclass STPAddCardViewController

### ISSUE THREAD

**Issue by tibo9** [stripe/stripe-ios#1921]
## Summary
It's not possible to subclass `STPAddCardViewController`
When subclassing, I've got this error : `Cannot inherit from non-open class ‘STPAddCardViewController’ outside of its defining module`

## Code to reproduce
`class MyCustomController: STPAddCardViewController`

## iOS version
15.2

## Installation method
SPM

## SDK version
21.9.1

## Other information
This was possible on previous versions.

**Comment by tibo9** [comment]
Thanks for your answer.

The previous version I was using and that enable subclassing is `16.0.5`.
I'm subclassing this controller, because I want it to match my MVVM architecture pattern.
I'm linking a view model to the controller to perform some actions before and after the payment mean update.

I tried a workaround and added the `SPTAddCardViewController` as a child of my custom controller. This is not the best solution because the `SPTAddCardViewController`'s navigation controller logic is broken.

**Comment by ramont-stripe** [comment]
@tibo9 thanks for the information! I have one more question: When you were subclassing `SPTAddCardViewController`, did you override any specific methods? or simply making your subclass conform to `STPAddCardViewControllerDelegate` and setting the delegate to `self`?

**Comment by tibo9** [comment]
You're totally right. 
My custom view controller conform to `STPAddCardViewControllerDelegate` and i'm setting the delegate to `self`.
My custom view controller also conforms to `STPAuthenticationContext`.
The overrode functions are the following : `viewDidLoad` and `loadView`.

**Comment by ramont-stripe** [comment]
Thanks @tibo9!

Prior to `v21.0.0` the Stripe SDK used to be written in Objective-C, which lacked granular access control and allowed subclassing any public exported class.

On `v21.0.0` we migrated the SDK to Swift, which has a [more robust access control](https://docs.swift.org/swift-book/LanguageGuide/AccessControl.html#:~:text=and%20so%20on.-,Access%20Levels,-Swift%20provides%20five) system and because of this certain classes cannot longer be subclassed as we originally intended.

I think that a workaround could be to wrap `STPAddCardViewController` in a custom navigation controller as follows:

```swift
class MyCustomController: UINavigationController {
    private let addCardVC = STPAddCardViewController()

    init() {
        super.init(rootViewController: addCardVC)
        // ...
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        addCardVC.delegate = self
    }
}

extension MyCustomController: STPAddCardViewControllerDelegate {
    func addCardViewControllerDidCancel(_ addCardViewController: STPAddCardViewController) {
        print("Cancel")
        // ...
    }

    func addCardViewController(
        _ addCardViewController: STPAddCardViewController,
        didCreatePaymentMethod paymentMethod: STPPaymentMethod,
        completion: @escaping STPErrorBlock
    ) {
        print("Created")
        // ...
    }
}

extension MyCustomController: STPAuthenticationContext {
    func authenticationPresentingViewController() -> UIViewController {
        return self
    }
}
```

Let me know if this solution works for your use case. If not, I can look into making the controller `open`.

**Comment by tibo9** [comment]
Thanks for the workaround ! 

This is working if you have to present the navigation controller. 
Unfortunately, for my use case, it's not possible. I have to push my subclass controller in an existing navigation controller.

**Comment by ramont-stripe** [comment]
If pushing to navigation controller, you can try overriding the `navigationItem` var as follows:

```swift
class MyCustomController: UIViewController {
    private let addCardVC = STPAddCardViewController()

    override var navigationItem: UINavigationItem {
        return addCardVC.navigationItem
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        addChild(addCardVC)
        view.addSubview(addCardVC.view)
        addCardVC.delegate = self
    }
}
```

This should solve the navigation bar issue that you were experiencing.

I started exploring the option of marking `STPAddCardViewController` as `open` today, but it will take a lot of API cleanup to remove the number of internal required initializers that otherwise will need to be exposed and implemented by subclasses.

**Comment by tibo9** [comment]
This last solution is working for me. Previously I was trying this kind of work around by setting the `navigation.rightBarButtonItem` with the child `rightBarButtonItem` but it was not working. Overriding the property works.

For my case, allowing the subclassing of the controller is not needed any more, so thanks a lot !

**Comment by ramont-stripe** [comment]
Thanks for the update! I'm closing this issue for now. Feel free to re-open or report a new issue if needed. We are happy to help :)
