### ISSUE TITLE
Default payment setup shows "Pay" rather than "Setup" for Apple Pay 

### ISSUE THREAD

**Issue by sowsan** [stripe/stripe-ios#1938]
Hello - it is been redirected to open the issue here. Please check here for more info https://github.com/flutter-stripe/flutter_stripe/issues/636

**Comment by ramont-stripe** [comment]
Hi @sowsan, thank you for reporting this. Technically the button reads "Apple Pay", not just "Pay" as it currently displays the Apple Pay logo (Pay). We cannot change the button to read "Setup" because we are required to use one of the Apple-approved captions.

Currently there an option to make it read "Set Up Pay", but the guidelines suggest that it should be used for setting up Apple Pay on the device that doesn't have Apple Pay set up yet.

> When a device supports Apple Pay, but it hasn’t been set up yet, you can use the Set up Apple Pay button to show that Apple Pay is accepted and to give people an explicit opportunity to set it up.
>
> <img width="239" src="https://user-images.githubusercontent.com/88752322/158687207-7d72700e-6b26-4c19-b58b-78986b06a72a.png">
>
> You can display the Set up Apple Pay button on pages such as a Settings page, a user profile screen, or an interstitial page. Tapping the button in any of these locations should initiate the process of adding a card.

[Source.](https://developer.apple.com/design/human-interface-guidelines/apple-pay/overview/buttons-and-marks/)

I will share this feedback with our design team so they are aware that the current experience can be a bit confusing.

**Comment by sowsan** [comment]
Thanks for the information @ramont-stripe . Once we click on Apple Pay button it shows the apple pay screen to complete the transaction which in our case there is no a charge yet and user is trying to setup their preferred payment option for future usage.

**Comment by ramont-stripe** [comment]
In order to setup Apple Pay for future usage we need to present [`PKPaymentAuthorizationViewController`](https://developer.apple.com/documentation/passkit/pkpaymentauthorizationviewcontroller) for the user to authorize the future transactions. Without this we cannot access the payment information.

The Apple Pay UI should say "Amount Pending". And If I remember correctly the prompt will say "Pay with Touch ID" when running on the Simulator, but it will say something along "Confirm with [Side Button/Touch ID]" when running on a real/physical device.

Unfortunately this behavior is something outside of our control, as most of the UI is controlled by iOS.

**Comment by ramont-stripe** [comment]
Closing this issue for now. Feel free to re-open if needed.
