### ISSUE TITLE
Custom action after user click delete saved card

### ISSUE THREAD

**Issue by zhiyao92** [stripe/stripe-ios#1988]
## Is your feature request related to a problem? Please describe.
Currently, deleting a saved card is just swipe to delete or through the edit button and pressing the delete button. 

## Describe the solution you'd like
The solution I was thinking is, when a user delete a saved card, I would like to show some alert or run some API call on our backend. And when the user selected ok on the alert or when the API return a response, it will proceed to delete the card. 

## Describe alternatives you've considered
Tried checking on the `paymentContextDidChange`, but with that the user has already deleted the card, and I couldn't try to slip in any code to show alert or do API call. Or if I am doing it wrong, please point me the right direction.

**Comment by wooj-stripe** [comment]
Hi @zhiyao92 -

Instead of implementing this on the frontend app, your backend may want to listen to webhooks so that you can make your API call when this happens.  I believe the webhook you are looking for is:

https://stripe.com/docs/api/events/types#event_types-payment_method.detached

I am optimistically closing this ticket, but feel free to re-open if you have any questions.
