### ISSUE TITLE
[BUG] Wechatpay-use-SDK branch, Xcode14 will report the following error: Stored Properties cannot be marked literature unavailable with '@available'

### ISSUE THREAD

**Issue by pangde** [stripe/stripe-ios#2010]
Hello, we are currently using Wechatpay-use-SDK branch, Xcode14 will report the following error: Stored Properties cannot be marked literature unavailable with '@available'. May I ask whether we should update to other branches or wait for you to fix wechatpay-use-SDK branch?

**Comment by ffedelefrsf** [comment]
Hey there,

I faced the same issue when updating my Mac today and XCode updated to v. 14, I just solved it by updating Stripe from 2.6.0 to 2.7.1. In my case, I'm using @stripe/stripe-react-native, so I first needed to update that package to the newest version (0.18.1) and then run `pod deintegrate && pod install`, in order to update Pods.

Note: I needed to upgrade minimum deployment iOS target version to 13 or above as well. This was for Stripe to get upgraded to v. 2.7.1 or above, and you can make it by updating Podfile (platform :ios, '13.0') and then change the minimum version on XCode selecting your target and then General. Of course, you will need to reinstall pods as described before to get these changes applied.

**Comment by davidme-stripe** [comment]
Closing this older issue — let us know if you're still experiencing this issue. Thanks!
