### ISSUE TITLE
Issue with carthage?

### ISSUE THREAD

**Issue by istx25** [stripe/stripe-ios#210]
I receive:

```
A shell task failed with exit code 66:
xcodebuild: error: Scheme StripeiOSStaticWithoutApplePay is not currently configured for the build action.
```

Have you shared the `StripeiOSStaticWithoutApplePay` scheme?

**Comment by jflinter** [comment]
Hmm, that scheme no longer exists, and I don't believe there are any remaining references to it. Try running `rm -rf ~/Library/Caches/org.carthage.CarthageKit` and then a fresh `carthage update`?

**Comment by istx25** [comment]
Didn't fix.

**Comment by istx25** [comment]
Would this be considered a Carthage issue then? Should I create an issue on that repository?

**Comment by istx25** [comment]
I have another entry in my `Cartfile` and that seems to go through.

**Comment by jflinter** [comment]
Hmm, what's in your `Cartfile` at the moment?

**Comment by istx25** [comment]
My `Cartfile` includes:

```
github "stripe/stripe-ios" "master"
github "linehop/SAMTextView" "master"
```

**Comment by jflinter** [comment]
Yeah, that Cartfile is working fine for me, so I suspect it's some kind of
caching issue. Some ideas:
- Remove the entire Carthage directory in your project (as well as the
aforementioned cache) and rerun `carthage update`
- Delete the contents of your DerivedData folder and retry
- Make sure Carthage is up-to-date (`brew update && brew upgrade carthage`)
- Open an issue with Carthage (as that is likely the culprit here, and not
this repository)

**Comment by istx25** [comment]
Okay. Thanks @jflinter. I tried deleting my DerivedData and updating Carthage first, but neither fixed the issue. Removing the entire Carthage directory and rerunning `carthage update` fixed the problem. I'm still going to open an issue on Carthage's repo as I think this *bug* could be fixed to avoid any frustration in the future.
