### ISSUE TITLE
Payment Sheet | iOS |  The Validation is missing when entering an Invalid Card Number. 

### ISSUE THREAD

**Issue by parkerbo** [stripe/stripe-ios#2131]
**Describe the bug**
When adding a payment method via presentPaymentSheet, an invalid card number is not validated (an error message does not appear) until the user selects a different field. It also does not autofocus to the expiry input, it stays on the credit card input field with no error shown until a user enters a valid card number, or selects a different field to trigger the error message.
**To Reproduce**
1. Initialize and present a payment sheet (can be setup intent or payment intent) 
2. Enter an invalid credit card
3. Notice no error message is shown.
4. Select a different  input field - error message is now shown

**Expected behavior**
I expected the input field to display an error message after entering a 16 digit invalid card number, or I expect an autofocus to the expiry input and display an error message.

**Video**
https://user-images.githubusercontent.com/9536856/201494793-b9200dc2-47a6-44cd-b191-8011a0b9f421.mp4

**Smartphone (please complete the following information):**
 - Device: any iPhone 
 - OS: iOS 16.1
 - Expo SDK: 46
 - Stripe-react-native version: 0.20.0

**Comment by porter-stripe** [comment]
Hi @parkerbo 👋 

This is expected behavior. The card number is only validated once we can confirm the user has finished entering a card number. This is because while a user is typing out their card number, it could be in an invalid state, and we don't want to show the error message while they are typing. We only want to show the error once we are confident they have finished entering the card number.
