### ISSUE TITLE
AccountCreateParams from java equivalent on IOS SDK?

### ISSUE THREAD

**Issue by avillegasG** [stripe/stripe-ios#2191]
there is a equivalent for AccountCreateParams from java on IOS SDK? im searching for account obj but can't find

**Comment by eurias-stripe** [comment]
Hi @avillegasG, no, this is not available by design, creating an account requires a secret key and secret keys shouldn't be exposed to clients, these kind of operations should be performed on your server.
You can read more about secret key usage at https://stripe.com/docs/keys.
And you can find some sample code creating an account server side [here](https://github.com/stripe-samples/connect-onboarding-for-express/blob/main/server/java/src/main/java/com/stripe/sample/Server.java).
Hope this helps.
