### ISSUE TITLE
Not able to place order getting 500 error 

### ISSUE THREAD

**Issue by kamarshad** [stripe/stripe-ios#223]

**Comment by jflinter** [comment]
Hello,
It appears you've removed your comment, but from reading it earlier I suspect your issue is happening on your own backend (your error messages don't look like they were coming directly from the Stripe API). If you're receiving errors along the lines of "token not found", I'd ensure that you're using matching API keys between your iOS app and your backend (i.e. your iOS app should use a [test/live] publishable key, and your backend should use a [test/live] secret key).
