### ISSUE TITLE
Swift 2?

### ISSUE THREAD

**Issue by houmanka** [stripe/stripe-ios#238]
Hi guys,

When will this be released for Swift 2? 

Thanks

**Comment by houmanka** [comment]
Also since I upgraded the Xcode and using the Swift 2. I get " No module found Stripe " Error!!!

**Comment by felixdkatt** [comment]
Check your header paths. Looks like xcode is no longer auto adding those from cocoa pods

**Comment by felixdkatt** [comment]
you need to add the applepay folder, publicheaders, and ui

**Comment by felixdkatt** [comment]
I fixed my stripe.h not found but im getting this

PaymentController.swift:208:75: Invalid conversion from throwing function of type '(<<error type>>, NSError!) throws -> Void' to non-throwing function type 'STPCompletionBlock' (aka '(Optional<STPToken>, Optional<NSError>) -> ()')

I think its because of ios 7's new ErrorType instead of NSError. 

can anyone verify?

**Comment by jflinter** [comment]
@houmanka, our SDK is fully compatible with swift 2 - it sounds like you may be having some installation errors related to Cocoapods, but it's hard to say without more context. @felixdkatt, it sounds like you're having a type mismatch in your own code - none of our APIs will throw any swift errors, as they're written in objective-c.

**Comment by felixdkatt** [comment]
here is where i'm getting the error

STPAPIClient.sharedClient().createTokenWithPayment(payment, completion: { (token: STPToken!, error: NSError!) -> Void in

xcode highlights this call and gives the
