### ISSUE TITLE
[Bug] VisionOS Support - is unavailable in VisionOS

### ISSUE THREAD

**Issue by JazKingX** [stripe/stripe-ios#3192]
## Other information

<img width="1507" alt="Screenshot 2024-01-21 at 23 24 51" src="https://github.com/stripe/stripe-ios/assets/21957803/65b748e8-a643-4f01-bad0-9c5c1b93719c">

**Comment by seanzhang-stripe** [comment]
Hi @JazKingX VisionOS support is already added since SDK version [23.20.0](https://github.com/stripe/stripe-ios/blob/master/CHANGELOG.md#23200-2023-12-18). Can you update to the latest version and try again?

**Comment by JazKingX** [comment]
Hi @seanzhang-stripe, I've spent a day repeating the following steps

1. Remove Stripe
2. Close Xcode
3. Delete derived data
4. Reopen Xcode
5. Add Stripe Package and set version
6. Rebuild 
7. Errors
8. Reset Package Cache
9. Rebuild
10. Errors
11. Repeat


<img width="849" alt="Screenshot 2024-01-22 at 19 44 08" src="https://github.com/stripe/stripe-ios/assets/21957803/09615fc2-d9cb-4380-a34e-cb8a2e68793d">

**Comment by JazKingX** [comment]
The package seems up to data

<img width="1512" alt="Screenshot 2024-01-22 at 20 36 09" src="https://github.com/stripe/stripe-ios/assets/21957803/d7c471bd-665c-4bf8-a9c3-e9702bad7059">

**Comment by davidme-stripe** [comment]
If you're using PaymentSheet, can you import the StripePaymentSheet [module](https://github.com/stripe/stripe-ios?tab=readme-ov-file#modules) instead of `Stripe`? StripePayments and StripePaymentsUI should work as well if you're using the card field or a custom UI. We don't plan to support Basic Integration on visionOS.
