### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by ChrisBeeson** [stripe/stripe-ios#344]
I've just updated my cocoa pods in my project and quite alarmingly notice that you have removed OSX from the pod spec. Is this intentional? 

If so how am I to continue using stripe in my OSX project?

Thanks

**Comment by jflinter** [comment]
Hi, yes, we've unfortunately discontinued OSX support in our SDK due to lack of interest (which I'm sure is of little consolation to you).

Fortunately, we publish binaries with each release on our github releases page, so you can download the last supported version (v7.0.0) directly [here](https://github.com/stripe/stripe-ios/releases/download/v7.0.0/StripeOSX.zip) and just drag it into your .xcodeproj.

**Comment by innovative1** [comment]
I notice this issue is closed, but I have a question regarding this. Since OSX support has been dropped, is it safe to use the old (v7.0.0) framework in new OSX apps or is it advisable to find another solution? Specifically, how long will this framework be reliable, for instance, if breaking changes are introduced in a newer version of the iOS library?

**Comment by jack-stripe** [comment]
@innovative1 - the underlying APIs are not going anywhere, so that version is safe to use for the foreseeable future.
