### ISSUE TITLE
Module 'Stripe' not found

### ISSUE THREAD

**Issue by mightyG** [stripe/stripe-ios#369]
I'm following the getting started information to add Stripe. When adding @import Stripe; in app delegate i get an error saying Module 'Stripe' not found.

**Comment by benzguo** [comment]
Hey there – what installation method are you using?

**Comment by mightyG** [comment]
Hello I'm using cocoapods

Date: Mon, 11 Jul 2016 09:56:42 -0700

**Comment by Ramseatina** [comment]
Hello, same problem. Install with CocoaPods.

**Comment by benzguo** [comment]
Hey there – just noticed that you're using @import. We don't support module imports right now – can you try replacing `@import Stripe;` with `#import <Stripe/Stripe.h>`?

Let me know if you have any other questions!

**Comment by mightyG** [comment]
But accordig to the documentation @import Stripe should be used. I tried using #import <Stripe/Stripe.h> it returns apple mach-o linker error.

**Comment by benzguo** [comment]
@mightyG – looked into this a bit more, and I believe `@import Stripe;` isn't working for you because cocoapods is integrating your dependencies as static libraries ([more info](https://blog.cocoapods.org/CocoaPods-0.36/)). Can you try adding `use_frameworks!` to the top of your Podfile?
```
platform :ios, "8.0"
use_frameworks!
...
```

You should then be able to use `@import Stripe;` – if you encounter any issues after that, can you share the full error message here, as well as your Podfile?

**Comment by mightyG** [comment]
Hello, you were right adding platform :ios, "8.0"
use_frameworks!made the thing work. But I had to clean my project and rebuild it.Thank you for your help.
Date: Tue, 12 Jul 2016 17:29:01 -0700

**Comment by ktgriffiSFU** [comment]
Thanks too both of you! you saved me a lot of time with your detailed responses.

**Comment by surayashivji** [comment]
If this wasn't fixed by uncommenting the Podfile line and reinstalling, are there any other tips of what to do?

**Comment by bdorfman-stripe** [comment]
Hey @surayashivji,

I recommend writing in to support@stripe.com, as we have a full team that helps people with integration issues. They can help troubleshoot your local setup.

Brian
