### ISSUE TITLE
init(coder:) error

### ISSUE THREAD

**Issue by JChung37** [stripe/stripe-ios#397]
For some reason every time, I run the example app I get this error "fatal error: init(coder:) has not been implemented:". I followed everything exactly and I don't know what it is. Is there anything that I'm missing here?

**Comment by benzguo** [comment]
@JChung37 That's odd – the example app doesn't use a storyboard, so you shouldn't ever see the trap on this line [0]. Have you made any modifications to the project? If you have, I recommend cloning the repo again, filling in your publishable key here [1], and running "Stripe iOS Example (Simple)".

[0] https://github.com/stripe/stripe-ios/blob/master/Example/Stripe%20iOS%20Example%20(Simple)/CheckoutViewController.swift#L102
[1] https://github.com/stripe/stripe-ios/blob/master/Example/Stripe%20iOS%20Example%20(Simple)/CheckoutViewController.swift#L16

**Comment by JChung37** [comment]
I used a storyboard in my application and followed the sample app to add Stripe to my app. How can I use this code if I also use a storyboard?

**Comment by JChung37** [comment]
@benzguo

**Comment by benzguo** [comment]
@JChung37 It sounds like you're copying `CheckoutViewController.swift` directly and using it in your storyboard. Keep in mind that this is just sample code – `CheckoutViewController` was written for our example app, and can't be initialized from a storyboard without some modification. (View controllers loaded from storyboards or xibs use `init?(coder:)`, and we didn't implement this in our example app because it doesn't use a storyboard).

**Comment by JChung37** [comment]
Do you know exactly how I could do this with a storyboard. I've searched up some various things, but I can't seem to get it to work. @benzguo
