### ISSUE TITLE
cannot find more objects of STPCheckoutInternalUIWebViewController

### ISSUE THREAD

**Issue by MarcSteven** [stripe/stripe-ios#398]
To make it easier to diagnose your issue, please fill out the following:

## Summary

When I imported it into my project show me.
The errors as below:

1, Property 'checkoutController' not found on object of type 'STPCheckoutInternalUIWebViewController
2, Property 'checkoutController' not found on object of type 'STPCheckoutInternalUIWebViewController *' *'
3, Property 'checkoutController' not found on object of type 'STPCheckoutInternalUIWebViewController
4, Property 'checkoutController' not found on object of type 'STPCheckoutInternalUIWebViewController 

*' *'## Code to reproduce

If possible, please include a brief piece of code (or ideally, a link to an example project) demonstrating the problem you're having.

## iOS version

iOS 9.0 ,programming language :Swift 

## Installation method

How did you install our SDK?
I installed it via cocoa pods 

## SDK version
4.0

**Comment by benzguo** [comment]
@MarcSteven v4.0 is a pretty old version of the SDK – we've since deprecated and removed all Checkout functionality, and added some [exciting new features](https://stripe.com/blog/ui-components-for-ios). Here's our changelog [0] – if possible, you should update to the latest version of the SDK.

[0] https://github.com/stripe/stripe-ios/blob/master/CHANGELOG

**Comment by MarcSteven** [comment]
Thank you so much.
