### ISSUE TITLE
[BUG] No such module 'StripePaymentSheet' inside freshly cloned git clone to checkout Example

### ISSUE THREAD

**Issue by nedimf** [stripe/stripe-ios#4166]
## Summary

PaymentSheetExample target will not build, failing with error: 
 No such module 'StripePaymentSheet'

## Code to reproduce

No code, just git clone directory and try opening in Xcode I tried, clean build folder multiple times.

## iOS version

18.0 Simulator
## Installation method

Git clone
## SDK version

Latest git clone from master branch

**Comment by joyceqin-stripe** [comment]
Hi @nedimf, instead of opening PaymentSheetExample from Xcode, try opening stripe-ios/Stripe.xcworkspace in Xcode and running with the PaymentSheetExample scheme. If that still doesn't work, I'd love to point you to our support channel on [our Discord](https://stripe.com/go/developer-chat), where we have engineers ready to help you 24/5. Thank you!
