### ISSUE TITLE
[Feature] Difficulties to use CustomerSheet just to add/save a payment method

### ISSUE THREAD

**Issue by mikehaydan** [stripe/stripe-ios#4172]
## Is your feature request related to a problem? Please describe.
We have deferred payments and if payment will be removed from CustomerSheet, without our server control, users may lose money.
We need to use a CustomerSheet just to add a payment method without displaying saved ones. Or, at least, do not allow to remove a payment method. 

## Describe the solution you'd like
Possible solutions:
- Add an easy way just to add a payment method 
- Or do not allow to edit payment method. 
- Or dismiss bottom sheet after adding a payment method.

## Describe alternatives you've considered
I tried to use a custom adapter, which overrides `fetchPaymentMethods`:

```
final class AppStripeCustomerAdapter: StripeCustomerAdapter {

    override func fetchPaymentMethods() async throws -> [STPPaymentMethod] {
        []
    }
}
```

But, in this case, after adding a payment method, bottom sheet display an empty list, which might be confusing for the users (See screenshots below):

## Additional context
![Screenshot 2024-10-22 at 09 49 02](https://github.com/user-attachments/assets/66360676-8097-4ba0-89f2-a41016a1efb4)
![Screenshot 2024-10-22 at 09 49 23](https://github.com/user-attachments/assets/d4f820e1-7365-41c3-84fb-315487c70a0f)

**Comment by seanzhang-stripe** [comment]
Hi @mikehaydan you can already achieve it with PaymentSheet. Here's how it works
- Create a SetupIntent for a customer
- Initialize the PaymentSheet with the SetupIntent clientSecret, don't set `customer` on PaymentSheet.Configuration() 
-  Present the PaymentSheet

The PaymentSheet won't display existing saved payment method because `customer` is absent from PaymentSheet.Configuration() , and PaymentSheet doesn't provide options for a customer to remove payment methods.

Hope this is helpful, let me know if you have any other questions.

**Comment by mikehaydan** [comment]
hi @seanzhang-stripe that works great. thanks
