### ISSUE TITLE
[BUG] Cannot Close PaymentSheet.FlowController

### ISSUE THREAD

**Issue by aomathwift** [stripe/stripe-ios#4299]
## Summary

I am currently migrating from Basic Integration to Mobile Payment Element.
In the process, I use `PaymentSheet.FlowController` to collect payment methods in the setup flow. However, after displaying the `PaymentSheet.FlowController`, I am unable to close the bottom sheet using the dismiss button.

Upon debugging, I noticed that pressing the close button triggers the `PaymentSheetFlowControllerViewController.didDismiss(didCancel:)` method. However, in this method, `flowControllerDelegate` is nil, which prevents `flowControllerViewControllerShouldClose` from being executed.

<img width="940" alt="スクリーンショット 2024-11-24 23 21 52" src="https://github.com/user-attachments/assets/ce8c291b-c207-4757-b9cd-705c19a9dc47">

Is this a bug, or am I missing some required configuration?
I would appreciate any advice or guidance.

## Code to reproduce

```swift
paymentSheetFlowController.presentPaymentOptions(from: self)
```

1. Present the PaymentSheet.FlowController
3. Press the dismiss button
4. Cannot close PaymentSheet.FlowController

## iOS version

18.0

## Installation method

Cocoapods

## SDK version

23.32.0

## Other information

Incidentally, the PaymentSheet can be closed successfully.

**Comment by davidme-stripe** [comment]
Hi @aomathwift, thanks for filing this!

It looks like your app may not be holding a strong reference to the PaymentSheetFlowController: Can you confirm that you're storing the result of `PaymentSheet.FlowController.create` somewhere before calling `presentPaymentOptions`?

We can fix the issue with the close button, but I don't think the integration will be usable unless you retain the PaymentSheetFlowController, as otherwise you won't be able to call `confirm()` to confirm the payment.

**Comment by aomathwift** [comment]
Hi @davidme-stripe, thank you for your advice.

As you pointed out, I was not retaining a strong reference to PaymentSheet.FlowController.
By adding a strong reference to PaymentSheet.FlowController, I was able to close the bottom sheet successfully. 
You’re absolutely right—without a strong reference, it’s also impossible to call `confirm`.
Thank you so much!

**Comment by davidme-stripe** [comment]
Great, thanks so much for following up! We'll also issue a fix in the next update to allow closing FlowController even if it isn't retained.
