### ISSUE TITLE
Client create token success but server responses there is no token in server.

### ISSUE THREAD

**Issue by tranngoclinh88** [stripe/stripe-ios#434]
## Summary

Client create token success but server responses there is no token in server.
I'm using PaymentViewController in sample.
Only happen with iOS.

I saw that Stripe version in header of create token api is **2015-10-12** but in Website is **2016-07-06**

> <NSHTTPURLResponse: 0x174a2d220> { URL: https://api.stripe.com/v1/tokens } { status code: 200, headers {
>   "Content-Type" : "application\/json",
>   "Access-Control-Allow-Origin" : "*",
>   "Server" : "nginx",
>   "Access-Control-Allow-Methods" : "GET, POST, HEAD, OPTIONS, DELETE",
>   "Access-Control-Max-Age" : "300",
>   "Cache-Control" : "no-cache, no-store",
>   "Date" : "Thu, 01 Sep 2016 14:46:48 GMT",
>   "Stripe-Version" : "2015-10-12",
>   "Access-Control-Allow-Credentials" : "true",
>   "Content-Length" : "739",
>   "Connection" : "keep-alive",
>   "Strict-Transport-Security" : "max-age=31556926; includeSubDomains",
>   "Request-Id" : "req_97AoyhimmzzEb0"
> } }

## Info
iOS: 8.3 iPhone 6+
iOS 9.3 iPhone 5SE

SDK: from 8.0.4 to 8.0.6

**Comment by bdorfman** [comment]
It sounds like you are using the provided example app with our example Heroku backend and are experiencing trouble after upgrading, is this correct? Can you try removing the current version of the Heroku app you have running and deploy a new one?  (from https://github.com/stripe/example-ios-backend ) There have been recent changes to our example backend that might account for the error you are seeing, possibly switching to the latest version will resolve the issue.

**Comment by shyaken** [comment]
Hi bdorfman.
Can you explain more detail where the problem come from? 
Currently our android app and server can work normally. 
When Android create token I can see there's an api call to 'v1/tokens' on the logs
But the iOS after creating the token I check the logs on stripe dashboard, there's no api 'v1/tokens' called, so that when I call api charges on server, it response the token is invalid.
We tried to update the iOS example to latest but still face the same problem. Do we need to setting or do anything on our server? Or there's any special config on iOS library to make it work? 
Thanks

**Comment by tranngoclinh88** [comment]
@bdorfman 
I copy **PaymentViewController** into my project and run.
It called create token successfully but logs in website did not recognize any request from client.
But running your objective-c sample can create token.
So what are special configurations that I missed when using class **PaymentViewController**?

**Comment by bdorfman** [comment]
Ah I see. I think the problem here is `PaymentViewController` isn't meant to be directly copied into your own app, it is just meant as an example of how you might integrate the SDK. It relies on other classes in the example app to function properly, such as `ViewController` which does the actual charge via the `STPBackendCharging` protocol and `Constants.m` where you fill in your key and url to the example Heroku backend.

Instead of using `PaymentViewController` directly in your own app as-is, which is not intended nor supported, I would recommend following through the iOS integration guide on our site [here](https://stripe.com/docs/mobile/ios) to get the SDK properly set up with your app. It will walk you through how to do the setup and integration of the SDK into your own app's classes.

**Comment by tranngoclinh88** [comment]
@bdorfman 
Error here is function    

 [[STPAPIClient sharedClient] createTokenWithCard:self.paymentTextField.cardParams
                                          completion:^(STPToken* token, NSError* error) {};

return token without error but did not show in Website like this:
<img width="661" alt="screen shot 2016-09-03 at 7 03 16 pm" src="https://cloud.githubusercontent.com/assets/1511264/18224713/61bd3d54-7209-11e6-9f13-d9497b3a4569.png">.

I worked before. (1 week ago).

**Comment by tranngoclinh88** [comment]
I found my error.
I set stripe api key before register. Like this:

> [Stripe setDefaultPublishableKey:STRIPE_API_KEY];
> [Fabric with:@[[STPAPIClient class]]];

Thank for your support!

**Comment by bdorfman** [comment]
Great, glad you got it figured out!

**Comment by Milan3792** [comment]
I am facing exact same issue but couldn't find where the problem might be. Token is created successfully, I have 2 publishable keys in my app, with one key everything works great but for the other key server returns "No Such Token". Can somebody tell me how I can identify this issue? Thanks in advance.

**Comment by jflinter** [comment]
This is happening because the publishable key you're using in your app
doesn't correspond to the secret key that you're using to make your API
request on your server.

**Comment by Milan3792** [comment]
@jflinter I tried to debug entire code, and checked STPPaymentConfiguration in app, all the keys on client side and server side seems to be correct. Not sure how I can figure out as where keys are going wrong.
