### ISSUE TITLE
App has been rejected because of use an Apple Pay APIs

### ISSUE THREAD

**Issue by EvgenyKarkan** [stripe/stripe-ios#503]
## Summary

Info message from `Apple Resolution Center`:

> During review, we noticed that your app utilizes the Apple Pay API. However, we were unable to verify any integration of Apple Pay within your app.

> *Next Steps*

> If your app integrates Apple Pay, please indicate where in your app we can find Apple Pay functionality.

> If your app does not integrate Apple Pay functionality, please indicate this information in the Review Notes section for each version of your app in iTunes Connect when submitting for review.

> Once you reply to this message in Resolution Center with the requested information, we can proceed with review.

My app does not use Apple Pay feature, but uses Stripe SDK for credit card payments.
So my question is, - do I need for some extra steps to solve the issue, or I just have to provide comment that states that app does not use Apple Pay?

## iOS version

Deployment target - `iOS 8`

## Installation method

Manual

## SDK version

`6.2.0`

**Comment by jack-stripe** [comment]
Hello! I'm sorry you ran into this - it was our impression that Apple had removed this check.
We recommend just telling Apple that you're not using Apple Pay but that you're using the Stripe SDK which does reference those symbols. If they don't accept your app after that, let us know here.





On Wed, Nov 16, 2016 at 8:22 AM -0800, "Evgeny Karkan" <notifications@github.com> wrote:










Summary


Info message from Apple Resolution Center:



During review, we noticed that your app utilizes the Apple Pay API. However, we were unable to verify any integration of Apple Pay within your app.




Next Steps




If your app integrates Apple Pay, please indicate where in your app we can find Apple Pay functionality.




If your app does not integrate Apple Pay functionality, please indicate this information in the Review Notes section for each version of your app in iTunes Connect when submitting for review.




Once you reply to this message in Resolution Center with the requested information, we can proceed with review.



My app does not use Apple Pay feature, but uses Stripe SDK for credit card payments.

So my question is, - do I need for some extra steps to solve the issue, or I just have to provide comment that states that app does not use Apple Pay?
iOS version


Deployment target - iOS 8
Installation method


Manual
SDK version


6.2.0

**Comment by EvgenyKarkan** [comment]
Ok, I will add such comments and let you know about news.

**Comment by EvgenyKarkan** [comment]
Ok @jack-stripe, my app is ready for sale now, I guess my experience will be useful for other people.
Have a nice day.

**Comment by kousun12** [comment]
Just got hit with this too. :( Doesn't seem super predictable when they'll run this check; submitted two with the sdk simultaneously last week and our newer app was rejected, our older app went through just fine. maybe worth adding a build flag?

**Comment by luohui8891** [comment]
> Just got hit with this too. :( Doesn't seem super predictable when they'll run this check; submitted two with the sdk simultaneously last week and our newer app was rejected, our older app went through just fine. maybe worth adding a build flag?

Think so. 
Otherwise, I should tell Apple I didn't use Apple Pay every version for release.

**Comment by bbrighton** [comment]
Pardon me for jumping into the conversation but I think our experiences may be relevant.

One of our apps involves handling Apple Pay tokens but not generating them (it’s effectively the server in a client-server model). Over the last 3 update submissions, Apple has metadata-rejected it asking effectively the same question each time — "where is Apple Pay support and how can we see it?”

The first two times, I explained the difference directly on the review team feedback and all was good - the 2nd review pass approved it. After the third rejection, I added the explanation to the reviewer notes in the submission details and literally copied that into the response to the review team. It passed the third time as well.

I think if you have a special case, you may want to make sure that you document that in the reviewer notes _before_ submission in order to save everyone additional hassle.

-brad
