### ISSUE TITLE
Perform navigation bar config of STPPaymentMethodsViewController in viewDidLoad to allow for overriding

### ISSUE THREAD

**Issue by KieranLaffertySC** [stripe/stripe-ios#507]
To make it easier to diagnose your issue, please fill out the following:

## Summary

viewDidLoad is the most optimal place to put navigation bar configuration as it allows subclassers to override in the case that they want to customize the way the nav appears (i.e. put a hamburger nav button in top left instead of cancel). Currently to accomplish this you have to put navigation config in viewWillAppear: which isn't ideal.

## iOS version

10.2

## Installation method

Podfile

## SDK version

Latest
## Other information

Anything else you can include that'll make it easier for us to help you!

**Comment by bdorfman-stripe** [comment]
Hi @KieranLaffertySC, 

We just made some tweaks to how back bar button items are configured in a recent commit. Some of the configuration still happens in viewWillAppear (since we want to provide automatic cancel vs back and there isn't really a good place before that where we know where we are in the nav stack), but when the view controller's are at the root of the nav controller, you should be able to change their left bar button items after init and not have them overridden. It's in master now and will be out officially in our next release.

Hope this helps your use case! Let us know if you're still having issues.
