### ISSUE TITLE
ipv6 support?

### ISSUE THREAD

**Issue by vishnuag05** [stripe/stripe-ios#524]
I am getting this error in create
The "app name" server produced an error.
func paymentAuthorizationViewController(controller: PKPaymentAuthorizationViewController, didAuthorizePayment payment: PKPayment, completion: (PKPaymentAuthorizationStatus) -> Void) {
        STPAPIClient.sharedClient().createTokenWithPayment(payment) { (token, error) in
                
            } else if let error = error {
     
            }
        }
    }

getting error in this code.please help
## iOS version
ios 10.1.1

**Comment by bdorfman-stripe** [comment]
Are you receiving an error back from STPAPIClient createTokenWithPayment? You should double check to make sure you have set your publishable key correctly, as failing to do so will cause requests to fail. Otherwise, if you could provide more information on the exact error you are receiving that would help us debug your issue.

**Comment by vishnuag05** [comment]
I am testing it in adhoc link and description of error is - The "app name" server produced an error.

Moreover this setup works correctly in normal internet ipv4 I mean , I wan't aware of this issue until app store team pointed it out to add support for ipv6 . So I believe this error is because of ipv6 , does this sdk include support for ipv6?

**Comment by bdorfman-stripe** [comment]
The Stripe API is only available via ipv4, but NSURLSession and other iOS networking apis should be handling this for you since we are using hostnames and not direct ip addresses. 

It sounds like this is an integration issue and not an bug with the sdk itself. I would recommend writing in to Stripe support at https://support.stripe.com/email and they can try to help you get everything configured properly.
