### ISSUE TITLE
BUG.

### ISSUE THREAD

**Issue by patchthecode** [stripe/stripe-ios#564]
I cannot import stripe.

Using Xcode8.2, Swift 3
Import gives me error.

It only imports correctly when i change my XCode setting to Legacy instead of Custom.
What gives? :/

**Comment by bdorfman-stripe** [comment]
Hey @patchthecode, without more details I can't be exactly sure what you are seeing, but if you are having trouble integrating the SDK I suggest contacting Stripe support: https://support.stripe.com/

**Comment by patchthecode** [comment]
It is not a stripe issue.

I cannot import Stripe unless I set my XCode settings to Legacy build.
What other information do you want?

**Comment by bdorfman-stripe** [comment]
I'm not sure exactly what legacy setting you are referring to. If you mean the "Use Legacy Swift Language Version" flag, it is not required. You can see in our included Swift 3 example app that it is set to NO and the app builds correctly. The exact error you are seeing from Xcode may help to diagnose further.

What version of the SDK are you using? You might have an outdated version which does not have proper Swift support. Otherwise I again suggest talking to Stripe support, as they can help you out with all sorts of issues integrating the iOS SDK into your app. Hope that helps!
