### ISSUE TITLE
STPAddCardViewController customize back button

### ISSUE THREAD

**Issue by royherma** [stripe/stripe-ios#609]
![image](https://cloud.githubusercontent.com/assets/3466248/24467144/087e1136-14bc-11e7-9318-e29db38cdfde.png)

## Summary

I'm trying to modify the back button (text, color, font) of a `STPAddCardViewController` that i'm pushing onto my navigation controller. It seems that I can't get access to it/replace it.

## Code to reproduce

I've tried a number of ways to modify it, with no luck (see image above)

self.navigationController?.navigationBar.barTintColor = UIColor.red
        self.navigationController?.navigationBar.topItem?.hidesBackButton = true
        self.navigationController?.navigationBar.topItem?.leftBarButtonItem = UIBarButtonItem()
        self.navigationItem.hidesBackButton = true
        self.navigationItem.leftBarButtonItem = UIBarButtonItem(title: NSLocalizedString("Back", comment: "bar buttons"), style: .plain, target: self, action: #selector(PKAddCardViewController.popBack))

## iOS version

What version of iOS are you observing the problem on?
10.2

## Installation method

cocoapods

## SDK version

10.0

**Comment by bdorfman-stripe** [comment]
All Stripe view controller's should inherit from `STPCoreViewController` which has accessors for the back and cancel buttons they display (depending on whether they are the root view in a nav view or not). 

However, instead of trying to customize the nav bar by directly modifying its items, I suggest you use an `STPTheme` object. You can set a theme object on either your view controller or your navigation bar and then the Stripe view controllers will styling everything correctly based on the set colors and fonts. The theme property for the view controllers is declared in `STPCoreViewController` and a category for setting them just on the navigation bar (if you want to have the bar be a separate theme from the rest of the view controllers color and font choices) is in `UINavigationBar+Stripe_Theme.h`. If you are you using `STPPaymentContext` it also has a theme property that it passes along to all its created view controllers.

Hope that helps!

**Comment by royherma** [comment]
@bdorfman-stripe I have tried applying STPTheme, and dove down into the actual source files - I could not see any property that modifies the "back button". No matter which `STPTheme` properties I set. Are you sure this is possible at all?

**Comment by bdorfman-stripe** [comment]
STPCoreViewController sets either its backItem or cancelItem to the left bar button item depending on whether you are at the root of the nav hierarchy or not, and updates its appearance to the set theme in `updateAppearance`, which is called in several places. 

The example app offers several different theming options to show how STPTheme works, and they appear to be styling the back button correctly for all view controllers. 

Sorry I can't be more directly helpful. If you have some code sample you could send that reproduces your bug I could try to take another look.

**Comment by sssbohdan** [comment]
@royherma Have you solved this problem? I tried to inherit from STPAddCardViewController and change `tintColor` of barButtons but it doesn't work 
```
    override func viewDidLoad() {
        super.viewDidLoad()
        
        navigationItem.leftBarButtonItem?.tintColor = .white
        navigationItem.rightBarButtonItem?.tintColor = .white
    }
```

**Comment by bdorfman-stripe** [comment]
Hi @sssbohdanm,

As mentioned previously, you should use `STPTheme` and the associated setters to customize the look of the nav bar, as `STPCoreViewController` may otherwise overwrite your manually set tintColor with data from its set theme. 

All the Stripe view controllers should have a theme parameter in their init. You can also set it on `STPPaymentContext` and it will pass the theme through if you use that. There is also a category on `UINavigationBar` if you would like to set the navigation bar theme separately from the view controller contents.

Hope that helps. Please open a new issue or email support@stripe.com if you continue to have trouble.

**Comment by sssbohdan** [comment]
Hi @bdorfman-stripe , this approach doesn't work for me if i want different colors for navigation bar buttons and credit card view.

**Comment by bdorfman-stripe** [comment]
If you want different nav bar theming from the contents of the view controller, you can set a different STPTheme object onto the UINavigationBar (see `UINavigationBar+Stripe_Theme.h`). When the view controllers style their bar button items, if the nav bar has a different theme than themselves they use the nav bar's theme instead. This should hopefully get you the styling options you need.

**Comment by sssbohdan** [comment]
@bdorfman-stripe Thanks, it helped me, my problem was that I have used `STPTheme.default()` for navigationBar and controller. I have created distinct instance and everything starts working.

**Comment by GILL71** [comment]
@royherma Have you solved this problem
I try to rename backButtonItem only - how can I do this?
