### ISSUE TITLE
Disable code coverage

### ISSUE THREAD

**Issue by TofPlay** [stripe/stripe-ios#794]
## Summary

Code coverage has to be disabled for Carthage to work with Xcode 9.

Check Carthage/Carthage#2056 and Carthage/Carthage#2057.

## Code to reproduce

Try to submit an application with stripe
Apple send back an email with the message:
```
Dear developer,

We have discovered one or more issues with your recent delivery for "<your app>". To process your delivery, the following issues must be corrected:

Invalid Bundle - Disallowed LLVM instrumentation. Do not submit apps with LLVM profiling instrumentation or coverage collection enabled. Turn off LLVM profiling or code coverage, rebuild your app and resubmit the app.

Once these issues have been corrected, you can then redeliver the corrected binary.

Regards,

The App Store team
```

## iOS version

iOS 10 and iOS 11

## Installation method

Cartfile
```
github "stripe/stripe-ios" "ios11"
```

## SDK version

branche `ios11`

## Other information

None

**Comment by bdorfman-stripe** [comment]
This should be fixed in the latest release, 11.3.0, which just went up. Please switch to using the standard releases if you were previously using the `ios11` branch. The mainline releases should now support iOS11 correctly and the other unofficial branch is no longer supported.

Please open a new issue if you have any further trouble. Thanks for your report!
