### ISSUE TITLE
Keyboard not working in checkout webview

### ISSUE THREAD

**Issue by kueychuj** [stripe/stripe-ios#798]
Hi, I have a problem related to the stripe checkout webview fallback experience.
From [here](https://github.com/stripe/stripe-ios/issues/262),  

> Unfortunately, Checkout on the web requires the payment sheet to be opened in a separate tab. As this isn't possible in a web view, we render a fallback experience that isn't as good-looking.

I know the reason why the ui in webview is different from that in modern browser and I have no problem with that even it is not good-looking.

However, the keyboard in ios (8, 9, 10) is sometimes not functioning, I could not type any numbers in credit card field, especially when I press the backspace or try to insert numbers between the already entered numbers in the textfield.

Same problem does not exist in android.

Any help would be appreciated.

**Comment by joeydong-stripe** [comment]
Hi @kueychuj,

I highly recommend that you try building your checkout flow with native UI. Our [Standard Integration Guide](https://stripe.com/docs/mobile/ios/standard) should make this fairly painless. 

Otherwise, since the Stripe Checkout isn't built for mobile web use cases, I would try our [Stripe Elements Quickstart](https://stripe.com/docs/elements) to see if that offers better compatibility. Again, getting this to work on mobile web is probably the same effort as following our native guide.

If you're still stuck, please send us an email at support@stripe.com and we'll follow up with more details!

**Comment by sarakhater** [comment]
hello,
 some times, Keyboard not working in checkout webview  
can i know the reason for this issue?

**Comment by davidmcgrath-ts** [comment]
I might be experiencing this issue as well.  it happens in an iOS web view, but not in iOS Safari

we have padding in the container element (rendered by our code) so that the card input (just the icon. and text) looks like any other text input.  the Stripe library seems to be handling the user tapping on the container element and moving focus where it needs to go, inside the stripe-rendered iFrame.  however, in an iOS web view, tapping on the whitepace in the container element (that's not the iFrame) moves focus to what seems to be a dummy input that is rendered beside the iFrame.

I think this may be fallback behavior for some other platform, but it is incorrectly triggering here

the result is that the full keyboard pops up (rather than the number keyboard), and the card input doesn't scroll into view.  the user has to scroll up and tap the middle of the text box (switching focus to the correct input) for this to work.  interestingly, after that, tapping away and back on the whitespace brings up the correct keyboard

I hope that makes sense!

**Comment by csabol-stripe** [comment]
Hi @sarakhater and @davidmcgrath-ts This repository is for native iOS integrations. For issues with Checkout please reach out to Stripe support :) https://support.stripe.com/
