### ISSUE TITLE
paymentMethodsViewControllerDidFinish is called before it was set as the default source.

### ISSUE THREAD

**Issue by kaandedeoglu** [stripe/stripe-ios#799]
## Summary

When the user has no payment sources and they add one, the `paymentMethodsViewControllerDidFinish` method is called before it is set as the default source. This breaks the flows where the iOS client only collects cards and leaves the charging to the backend - which in turn checks if the Stripe customer has a default payment source. 

Is there any reason why the SDK doesn't wait for all the operations to complete before deciding that the work is done?

Manually setting the newly added source as the default source and then triggering the charging step, everything works out. (Except the fact that `STPPaymentMethodsViewController` stops its loading indicators seconds before it is dismissed).

## SDK version

v11.3.0

**Comment by joeydong-stripe** [comment]
Hi @kaandedeoglu, thanks for opening an issue. Let me dig into this and get back to you. Sorry for the delay!

**Comment by joeydong-stripe** [comment]
Hi,

I think the part of the codebase that you're referring to is [`[STPPaymentMethodsViewController 
 finishWithPaymentMethod:]`](https://github.com/stripe/stripe-ios/blob/master/Stripe/STPPaymentMethodsViewController.m#L179). In particular, the view controller calls [`[self.delegate paymentMethodsViewControllerDidFinish:self]`](https://github.com/stripe/stripe-ios/blob/master/Stripe/STPPaymentMethodsViewController.m#L198) in parallel with [`[self.apiAdapter selectDefaultCustomerSource:]`](https://github.com/stripe/stripe-ios/blob/master/Stripe/STPPaymentMethodsViewController.m#L182).

I believe this is an optimization so that the user can return to the checkout screen (after adding/selecting their payment method) without having to wait for the network request. We expect there to be a delay between the "return to checkout screen" and when the user actually taps the "buy" button which should trigger the charge.

Does this make sense with your integration? If not, can you give me some more details of what your checkout flow looks like?

**Comment by joeydong-stripe** [comment]
I'm going to close this issue for now. Feel free to continue the conversation here.

**Comment by kaandedeoglu** [comment]
@joeydong-stripe Thank you for the response. Our problem is now solved, it wasn't related to the related issue for most part. 

That being said, I still find the optimization to be unnecessary. For one, the time saved here is miniscule. 

Also, this causes a race condition. We can select a default payment method from `STPPaymentMethodsViewController`, and if a new `STPPaymentMethodsViewController` is presented right after, we see that the default card still hasn't changed. Here's a screen capture of the situation:


https://www.dropbox.com/s/jw3tzm0vkk62ye5/ScreenRecording_10-04-2017%2011%3A24.mp4?dl=0
