### ISSUE TITLE
STPCard.brandFromString Deprecation

### ISSUE THREAD

**Issue by crontab** [stripe/stripe-ios#800]
https://github.com/stripe/stripe-ios/blob/00d0547c4e8e46c57740934fd58178973acb5190/Stripe/PublicHeaders/STPCard.h#L210

This useful function is now deprecated, what is the suggested alternative?

**Comment by joeydong-stripe** [comment]
Hi @crontab, thanks for opening an issue.

We originally publicized this method unintentionally and recently decided to deprecate it because we didn't understand the use case for it. In particular, the `string` values are [specific to the Stripe API](https://stripe.com/docs/api#card_object-brand) which is tricky to handle. We primarily expect developers to use the `[STPCard brand]` method and `STPCardBrand` enum instead of passing the string value around.

Can you give us some information about how you are/will be using this method?

**Comment by crontab** [comment]
Hi @joeydong-stripe 

Our mobile app receives the card brand strings from our backend which in turn receives them from Stripe. The app among other things uses these strings to display card images to the user using your other API functions. Thus the string-to-numericID translation should happen somewhere, i.e. either on our backend (which we are a bit reluctant to do at the moment) or on the frontend/mobile side. This function did just that for us.

**Comment by joeydong-stripe** [comment]
Thanks for the extra context! This is definitely a tricky problem. We had some discussions and although there could be a problem if the Stripe API changes the [`brand`](https://stripe.com/docs/api#card_object-brand) identifiers, it is unlikely to happen.

Please see pull request https://github.com/stripe/stripe-ios/pull/801

**Comment by joeydong-stripe** [comment]
We've merged #801. The method will be un-marked as deprecated in the next release. Thanks again!
