### ISSUE TITLE
Stripe Token getting as 'card_xxxx' but API requires as 'tok_xxxxxxx'

### ISSUE THREAD

**Issue by Sadmansamee** [stripe/stripe-ios#816]
## Summary
For Stripe Connect 
On didCreatePaymentResult  Stripe Token getting as 'card_xxxx' but API requires as 'tok_xxxxxxx', How Do I get the token in the proper way?
so when calling to create charge getting response like 

> No such token: card_XXXXXXXXXXX

## Code to reproduce

`func paymentContext(_ paymentContext: STPPaymentContext, didCreatePaymentResult paymentResult: STPPaymentResult, completion: @escaping STPErrorBlock) {
        // Create charge using payment result
        let source = paymentResult.source.stripeID`

## iOS version

11.0.3

## Installation method

Standard Integration

## SDK version
11.3.0

**Comment by bg-stripe** [comment]
Hi @Sadmansamee ,

Because PaymentContext adds the card to a Stripe customer, you'll need to include the customer id when creating the charge.

Example:
https://github.com/stripe/example-ios-backend/blob/master/web.rb#L46-L53

We generally reserve Github issues for bugs and feature requests – if you'd like further help with your integration, please reach out to support@stripe.com .

**Comment by YahyaBagia** [comment]
Hey @Sadmansamee , were you able to get proper token (tok_xxxxx) insread of source (card_xxxx) in iOS app? I'm at the same situation as yours.
