### ISSUE TITLE
Crash (assertion failure) in 11.4.0 when getting ephemeral key fails

### ISSUE THREAD

**Issue by davidsantiago** [stripe/stripe-ios#819]
To make it easier to diagnose your issue, please fill out the following:

## Summary

When the SDK attempts to get the ephemeral key, it asks our backend API to provide one. We were previously on Stripe SDK 11.1, and sometimes our API would fail to get a key, returning an error. Stripe would gracefully handle this and retry, leaving the user oblivious to anything having gone wrong. 

We are trying to move to Stripe SDK 11.4, and now when our backend API returns an error, the entire app gets taken down by an assertion failure:

```
2017-10-30 00:05:00.871 Bird[29806:608463] *** Assertion failure in -[STPEphemeralKeyManager getCustomerKey:], /Users/davidsantiago/Documents/Work/ios/Pods/Stripe/Stripe/STPEphemeralKeyManager.m:106
2017-10-30 00:05:00.898 Bird[29806:608463] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not parse the ephemeral key response. Make sure your backend is sending the unmodified JSON of the ephemeral key to your app. For more info, see https://stripe.com/docs/mobile/ios/standard#prepare-your-api'
*** First throw call stack:
... etc ...
```

## Code to reproduce

There's no code to really reproduce, except to take a working app using the ephemeral key API, but where the backend is returning an error, and then do `pod update Stripe` to Stripe 11.4, and try again. So the key step is really to make the backend API endpoint return a 400 error instead of an ephemeral key, while using Stripe API version 11.4. 

## iOS version

We are seeing this on iOS 11. Can't easily test iOS 10 anymore. 

## Installation method

Cocoapods.

## SDK version

This is with version 11.4. We are upgrading directly from 11.1 to 11.4, so we're not sure when exactly this issue began.

**Comment by davidsantiago** [comment]
After working on this some more, it looks like you guys added the assert in STPEphemeralKeyManager.m:- (void)getCustomerKey:(STPEphemeralKeyCompletionBlock)completion at some point.

It is certainly the case that we were counting on being able to send an error response through to the Stripe SDK and have Stripe handle it OK. I don't know what your policy on backwards compatibility is (semantic versions, or what not), but it is a little surprising to be broken with a crash like this. I would argue that killing the process is not a good response to bad input from the API user, even if we should fix this ourselves.

**Comment by bdorfman-stripe** [comment]
Hey David,

As far as I can tell this assert has always been there (it blames to July 2017). Generally `NSAssert` calls are not actually included in Release builds because by default Xcode sets the `NS_BLOCK_ASSERTIONS`  preprocessor macro for Release configurations (accessible via the Xcode UI at "Build Settings" -> "Enable Foundation Asserts"). If you are just newly seeing this behavior, possibly your build configuration has changed and now you no longer have this setting enabled for your app store build?

**Comment by davidsantiago** [comment]
Yeah, we are using the same Stripe version (11.1) since before July, so that is definitely why it was working for us all this time. We haven't changed build settings, but I wasn't aware of that build setting, and didn't realize it wouldn't have terminated if I had done a release build. Clearly you guys did that deliberately, so I will code around it.

**Comment by bdorfman-stripe** [comment]
Sorry about the trouble. It was added so that it would fail early at the correct location for people who integrated their key provider incorrectly, which is a frequent issue.

Additionally, this code path should only be hit if you pass in neither a key nor an error (which is not a valid response for your key provider according to the documentation which is why I believe we did not consider this a breaking change). If you want our error handling when you get 400s from your server, making sure to pass through an NSError object should get you the functionality you desire. Let me know if this does not appear to work for you.

Brian

**Comment by davidsantiago** [comment]
Yep. When I added a workaround I saw that the issue was that Alamofire considers any response from the server to be a "success," so we were passing the error response as a success value. I was just surprised to find anything broken on a minor version upgrade (and this is only one of the many things that have broken for us on 11.1 -> 11.4).
