### ISSUE TITLE
STPAddCardViewController: Navigation title font does not use emphasisFont

### ISSUE THREAD

**Issue by pgor** [stripe/stripe-ios#822]
## Summary

`STPAddCardViewController` does not use a configured `STPTheme.emphasisFont` for the navigation bar title as the documentation indicates it should:

![stripe ios ui theming](https://user-images.githubusercontent.com/140783/32247421-84ae4528-be3f-11e7-9692-4cbfd88a6ae2.png)

## Code to reproduce

With a valid `configuration`, execute:

```swift
let theme = STPTheme.default()
theme.emphasisFont = UIFont(name: "MarkerFelt-Thin", size: 22)
let addCardViewController = STPAddCardViewController(configuration: configuration, theme: theme)
let navigationController = UINavigationController(rootViewController: addCardViewController)
present(navigationController, animated: true, completion: nil)
```

### Expected: 
<img src="https://user-images.githubusercontent.com/140783/32247448-a269e95a-be3f-11e7-8428-5a655fe740ec.png" width="50%" height="50%" alt="Expected">

### Observed: 
<img src="https://user-images.githubusercontent.com/140783/32247455-a96a1838-be3f-11e7-82bd-e5b1880a583f.png" width="50%" height="50%" alt="Observed">

## iOS version

 Observed in iOS 10.x and 11.x.

## Installation method

Cocoapods

## SDK version

Originally noticed in 11.2.0, still present in 11.4.0.

## Other information

It appears that the navbar's `stp_theme` is just never getting set. If I change `STPCoreViewController.m:83` from

```obj-c
STPTheme *navBarTheme = self.navigationController.navigationBar.stp_theme ?: self.theme;
```
to
```obj-c
STPTheme *navBarTheme = self.navigationController.navigationBar.stp_theme;
if ( navBarTheme == nil ) {
   navBarTheme = self.theme;
   self.navigationController.navigationBar.stp_theme = navBarTheme;
}
```
it works. I'm just not sure that's the preferred location to fix this.

**Comment by bdorfman-stripe** [comment]
Hi @pgor,

Sorry you're having trouble. I think the problem here might our docs are a little misleading in this image. We only set the navigation bar theme if you use one of the "push" methods in `STPPaymentContext`. If you create your own nav controller for presentation, or push one of our VC's onto an existing nav stack, we do not set the theme on the navigation bar. This is because changes to the nav bar would persist once the user has left our screens and returned to the rest of the app. We can only guarantee the changes are limited to our screens when we control the lifetime of the navigation controller, as in the `STPPaymentContext`. If you want to manually create a navigation controller, like in your example, you must manually set the theme using the `stp_theme` property in `UINavigationBar+Stripe_Theme.h`

I will make sure to update the documentation on our site to make this more clear. Sorry again about the confusion.

Brian
