### ISSUE TITLE
Change standard integration card number placeholder text?

### ISSUE THREAD

**Issue by LightD** [stripe/stripe-ios#844]
I'm using the `11.5.0` release of stripe SDK with iOS11, and I'm following the standard integration which pushes stripe UI and all is well.

Except that when I pushed to the appstore, apple complained that we shouldn't have "test placeholders" and attached a screenshot of stripe UI which has `4242 4242 4242 4242` as the card placeholder. 

So my question is, with standard integration, how do I change the placeholder text?

**Comment by bg-stripe** [comment]
Hi @LightD ,

Sorry to hear about the rejection! I think in this case the reviewer is simply confused about the nature of the placeholder text in our UI. The app store guidelines say your final app shouldn't include test placeholders, but the `4242 ...` placeholder in our UI is intentional, and meant to demonstrate to the user what to type into the field. You can refer to the third example on this page as evidence of this practice in another payment form: https://stripe.github.io/elements-examples/ 

Hopefully responding to this effect in the resolution center will be enough to get your app approved. We'll re-evaluate the `4242...` placeholder in upcoming versions, and consider replacing it with `Card number`.

Best,
Ben
