### ISSUE TITLE
three_d_secure from STPCard

### ISSUE THREAD

**Issue by parasdaff** [stripe/stripe-ios#858]
Hi,

is there any way to check three_d_secure in STPCard.

**Comment by bdorfman-stripe** [comment]
In order to use 3D secure, you must be using the sources API (STPSource) and not the tokens API (STPToken/STPCard). You should use `STPSourceParams cardParamsWithCard:(STPCardParams *)card` and `STPAPIClient createSourceWithParams:(STPSourceParams *)params completion:(STPSourceCompletionBlock)completion` methods to create your card source. Then you can access the three_d_secure information off the returned source at `source.cardDetails.threeDSecure`.

If you have further integration questions, I recommend writing in to support@stripe.com. They can help you set up the SDK with your app and answer any questions you run in to. Generally we reserve Github issues for bug reports only.

Thanks,
Brian
