### ISSUE TITLE
Can't enter redirect flow for 3DS verification with 3DS type "optional" card

### ISSUE THREAD

**Issue by erichsu** [stripe/stripe-ios#877]
## Summary

I am trying to charge a payment by 3DS credit card source method, and it works fine in Stripe iOS SDK 11.2. After migrate to 11.5, STPRedirectContext initializer return nil if the Source token is already in chargeable status.
(in commit: https://github.com/stripe/stripe-ios/commit/5de15501d899713cf9f736a9f073b94f2f7b7ebb)

Is there any way to force user to enter redirect flow for 3DS verification?

testing card no. 4242 4242 4242 4242 will not enter redirect flow
P.S. The weird part is, 4000 0000 0000 3055 works fine.
## Code to reproduce

Example code
```swift

    func startCharge(source: STPSource) {
        guard let redirectContext: STPRedirectContext = STPRedirectContext(source: source, completion: { (sourceId: String, clientSecret: String, err: Error) -> Void in
            
            print("Start polling callback")
            STPAPIClient.shared().startPollingSource(withId: sourceId, clientSecret: clientSecret, timeout: 10, completion: { source, err in
                
                if let source: STPSource = source {
                    
                    switch source.status {
                    case STPSourceStatus.chargeable:
                        print("chargeable")
                        
                        
                        
                        
                    case STPSourceStatus.consumed, STPSourceStatus.canceled, STPSourceStatus.pending, STPSourceStatus.failed, STPSourceStatus.unknown:
                        print("failed")
                    }
                    
                } else if let err: Error = err {
                    print("source: polling err \(err)")
                }
            })
        }) else {
            print("redirect context invalid")
            return
        }
        
        redirectContext.startRedirectFlow(from: nav)
    }
```

## iOS version

iOS 10.x and above

## Installation method

How did you install our SDK?
Carthage

## SDK version

Cartfile.resolved
github "stripe/stripe-ios" "v11.5.0"

**Comment by bg-stripe** [comment]
Hi @erichsu ,

According to our docs, 3DS sources are usually set to `pending`, but may be `chargeable`  if the customer’s card has not yet been enrolled in 3D Secure. If the 3DS source is `chargeable`, I believe you should not redirect the customer (since the card either doesn't need verification or does not support 3DS).

https://stripe.com/docs/sources/three-d-secure#checking-if-verification-is-still-required

To test 3DS, you should use the test card numbers [here](https://stripe.com/docs/sources/three-d-secure#3ds-cards). All other test cards (like `4242`) do not require verification and will immediately be set to chargeable.

Hope this helps. If you have any additional questions about your 3DS integration, please get in touch with support@stripe.com – they'll be happy to help you further.

Ben

**Comment by billinghamj** [comment]
Just because it's `chargeable` doesn't mean we necessarily want to charge it without additional verification.

If 3DS is optional, many merchants will still want to run the authentication process anyway - otherwise it will end up with `status` set to `succeeded`, but `authenticated` set to false.

This is something the Stripe docs explicitly mention as an option:

> `optional`: 3D Secure is optional. The process isn’t required but can be performed to help reduce the likelihood of fraud.

https://stripe.com/docs/sources/three-d-secure#check-requirement

**Comment by bg-stripe** [comment]
Ah, you're right @billinghamj – my apologies, it looks like this is a regression. We'll include a fix for  `RedirectContext` in the next release.
