### ISSUE TITLE
expirationPlaceholder not localizable of STPPaymentCardTextField

### ISSUE THREAD

**Issue by nicolasifd** [stripe/stripe-ios#925]
In line 162 of STPPaymentCardTextField.m 
`
    self.expirationPlaceholder = @"MM/YY";
`
it should have STPLocalizedString.

**Comment by joeydong-stripe** [comment]
Hi @nicolasifd, thanks for opening an issue.

While I don't disagree with you, it looks like the `expirationPlaceholder` is a set-able property. Does that work for you?

**Comment by nicolasifd** [comment]
Yes, I didn't notice it was a set-able property and it worked well.

**Comment by joeydong-stripe** [comment]
Sorry, actually now that I look at it again, I would not recommend changing the placeholder because it will always be interpreted as "MM/YY". We need to look into making the field "YY/MM" compatible.

See:
- https://github.com/stripe/stripe-ios/blob/0dd2dc2550e083186b86309285ef33f747099a32/Stripe/STPPaymentCardTextField.m#L1239
- https://github.com/stripe/stripe-ios/blob/1cf5109d1e0095c255450fd30706871bc9dab012/Stripe/STPPaymentCardTextFieldViewModel.m#L24

**Comment by nicolasifd** [comment]
Joey, what I needed was display the text in spanish as "MM/AA" (mes/año) more than change the order.
Thanks for the reply, my problem was solved, but maybe your pull will solve the problem in other language format.

**Comment by joeydong-stripe** [comment]
Ah I understand your case now. Thanks letting me know!
