### ISSUE TITLE
No good UI for allowing users to opt out of card saving

### ISSUE THREAD

**Issue by Klingefjord** [stripe/stripe-ios#958]
## Summary

We're looking into integrating support for saving cards. We have found a limitation in that there is no good way for users to opt out of having their details saved. It would be extremely valuable for us if there existed a checkbox component in the `addCardViewController` that we could use as a "remember me" button.

## Code to reproduce

We initiate the payment context with: 

`let paymentContext = STPPaymentContext(customerContext: customerContext,
                                               configuration: StripeUtil.createPaymentConfiguration(),
                                               theme: StripeUtil.getTheme())
paymentContext.hostViewController = sender
paymentContext.delegate = self`

We the present an `addCardViewController` with `paymentContext.requestPayment()`

## iOS version

iOS 11.3

## Installation method

CocoaPods

## SDK version

13.0.0.2

## Other information

I realize this may be more of a feature request than an issue, but since you were so good at responding to a previous problem we had with your SDK I thought I'd give it a shot. Furthermore it seems like a common usecase and something that would make sense to have in place

**Comment by joeydong** [comment]
Hi again @Klingefjord :)

We specifically had a feature called "Remember Me" that allowed users to opt-in remembering their credit card details when checking out with various Stripe businesses. We ended up removing that feature because it was confusing (users aren't aware what Stripe is among other reasons) so we got rid of it.

In this case, I think what you are attempting to do is to give the user an option to remove their saved credit card from the Customer object for your app once checkout is complete. Is that correct? Would providing an option to delete the payment method after successfully checking out be suitable to do from your app and not inside the `paymentContext.requestPayment()`?

**Comment by joeydong** [comment]
![simulator screen shot - iphone 8 - 2018-06-06 at 15 46 27](https://user-images.githubusercontent.com/434294/41068967-ca44af0c-69a0-11e8-94a5-f8f152a01c45.png)

In a related case, we do offer the option for users to delete payment methods from the UI as long as there is at least 1 payment method left.

**Comment by joeydong** [comment]
What about breaking up your checkout flow like our Simple Integration example does so that you can offer a "forget me" checkbox just above the "Buy" button?

![simulator screen shot - iphone 8 - 2018-06-06 at 15 47 33](https://user-images.githubusercontent.com/434294/41069037-04cc6142-69a1-11e8-8b27-9391a1062516.png)

**Comment by Klingefjord** [comment]
Hi, thanks for your answers! Just for the record, what we ended up doing was presenting the addCardViewController as a standalone vc (not with a payment context) and then added a checkbox to the addCardViewController's footer view. We then passed the source and the customer id and whether the card should be saved to the backend, where we linked the source to the customer if they wanted that. Maybe worth considering adding something like this out of the box, considering GDPR and all that?

**Comment by joeydong-stripe** [comment]
Ah great, thanks for the update. Sounds good!

> then added a checkbox to the addCardViewController's footer view

Nice! I forgot we offered this API:

https://github.com/stripe/stripe-ios/blob/master/Stripe/PublicHeaders/STPAddCardViewController.h#L58-L65
