### ISSUE TITLE
Month Validation returns incomplete for 1 (January)

### ISSUE THREAD

**Issue by Bhargow** [stripe/stripe-ios#974]
https://github.com/stripe/stripe-ios/blob/b17dd1265473a19b01b36dabc7e399359ea7bcff/Stripe/STPCardValidator.m#L65

In my app, I have added an extra validation for all the fields entered in the STPPaymentCardTextField 

Month 
Year
Card
CVV

I used the below code to validate the month

Note: viewPaymentDetails (this is the STPPaymentCardTextField object)

let expMonth = viewPaymentDetails.expirationMonth // NSUInteger
let expMonthState = STPCardValidator.validationState(forExpirationMonth: String(expMonth))
print(expMonthState.rawValue)

When the  expMonth == 1
expMonthState == .incomplete

Other than 1 everything works fine

I walked through the code in the SDK the line from the above link which says 
return ([sanitizedExpiration isEqualToString:@"0"] || [sanitizedExpiration isEqualToString:@"1"]) ? STPCardValidationStateIncomplete : STPCardValidationStateValid;

There seems to be an issue here. Could you please check.
Thank you

**Comment by joeydong-stripe** [comment]
Hi @Bhargow, thanks for opening an issue.

I believe the reason we say an entry of just "0" or "1" is incomplete is because the user can continue entering information to make it "01", "02", etc or "10", "11", "12". Thus, we cannot confidently determine that they intended to input "1" to mean "January". On the other hand, entering a "2" has no other valid possibilities so we can confidently determine the user intended "February".

What do you think?

**Comment by Bhargow** [comment]
Thank you for the quick reply, I totaly agree with you.

In the case of using STPPaymentCardTextField we need to use
**"let expMonth = viewPaymentDetails.formattedExpirationMonth"** instead of 
**"let expMonth = viewPaymentDetails.expirationMonth"**
 for the below code for proper validation
 let expMonthState = STPCardValidator.validationState(forExpirationMonth: expMonth)

But when we use custom textfields for design purposes,
Should we append 0 as a prefix if the user enters 1 for january for the validation to work as expected?
My concern is, if it could be more generic for all the designs that would be great.

Thank you.

**Comment by joeydong-stripe** [comment]
Hi @Bhargow,

If we look at the implementation of `STPCardValidator.validationState(forExpirationMonth:)`:

https://github.com/stripe/stripe-ios/blob/master/Stripe/STPCardValidator.m#L53-L71

Whether or not you prepend a `0` is up to you. If the user entered a `1` and you are sure they intended January, then yes, I would prepend a `0` to get `STPCardValidationStateValid` instead of `STPCardValidationStateIncomplete`.

Please reach out to support using the form at https://support.stripe.com/ (preferred) or via email to support@stripe.com for further assistance.

We reserve issues here for topics that you believe represent actual bugs or feature requests for the Stripe iOS SDK.

Thanks!
