### ISSUE TITLE
STPPaymentMethodsViewController uses Cancel button when pushed

### ISSUE THREAD

**Issue by bryanhathaway** [stripe/stripe-ios#975]
## Summary
STPPaymentMethodsViewController always shows "Cancel" as the left bar button item, even when pushed onto an existing navigation stack.

The expectation is that when pushed the button should be "< Back" or at the very least "< Cancel" with the chevron, to comply with user expectations of pushed controller behaviour.

## Code to reproduce
```
let controller = STPPaymentMethodsViewController(configuration: STPPaymentConfiguration.shared(),
                                                         theme: STPTheme.default(),
                                                         customerContext: stripeCustomerContext,
                                                         delegate: self)
 /*
(Shows Cancel button)
show(controller, sender: nil)

(Also shows cancel button)
navigationController?.pushViewController(controller, animated: true)

(Also shows cancel button) */
navigationController?.show(controller, sender: nil)
```

## iOS version
10.3.1
11.4

## Installation method
Cocoapods

## SDK version
13.0.3

## Other information
From what I can see from existing issues, the Back button is used as expected when dealing with a PaymentContext, but I'm just trying to push this controller on its own as per the [Custom Integration guide](https://stripe.com/docs/mobile/ios/custom)

**Comment by joeydong-stripe** [comment]
Hi @bryanhathaway, thanks for opening an issue.

We've decided to keep it as a "Cancel" button even if the view controller is pushed because the view controller can potentially lead the user to adding a new card. If that happens, the idea of always being able to "go back" doesn't hold up so "Cancel" is more appropriate.

If you want to change the behavior yourself, you can always fork this repository and make the change yourself :)

**Comment by joeydong-stripe** [comment]
Otherwise, I would suggest that you present the view controller instead. Nice attention to detail!
